export const extendedTranslations: Record<string, Record<string, string>> = {
  en: {
    '홈': 'Home', '프로젝트': 'Projects', '보고서': 'Reports', '프로젝트 불러오는 중…': 'Loading project…', '프로젝트를 찾을 수 없습니다.': 'Project not found.', '프로젝트를 저장하지 못했습니다.': 'Could not save the project.', '프로젝트를 불러오지 못했습니다.': 'Could not load the project.', '프로젝트를 보관했습니다.': 'Project archived.', '프로젝트 보관을 해제했습니다.': 'Project unarchived.', '프로젝트를 휴지통으로 이동했습니다.': 'Project moved to trash.', '프로젝트를 휴지통으로 옮겼습니다.': 'Project moved to trash.', '프로젝트와 연결된 모든 작업·보고서를 영구 삭제할까요? 이 작업은 되돌릴 수 없습니다.': 'Permanently delete this project and all associated work and reports? This cannot be undone.', '프로젝트를 휴지통으로 이동할까요? 작업과 보고서는 보관되며 휴지통에서 복구할 수 있습니다.': 'Move this project to the trash? Its work and reports will be kept and can be restored from the trash.', '뜨개 차트': 'Knitting chart', '사진 도안': 'Photo pattern', 'PDF 도안': 'PDF pattern', '정보 저장': 'Save details', '보관 해제': 'Unarchive', '변경을 되돌렸습니다.': 'Change undone.', '저장 중': 'Saving', '사진 바꾸기': 'Change photo', '크게 보기': 'View larger', '무늬단': 'Pattern row', '메인 카운터 추가': 'Add main counter', '추가 설정 접기': 'Hide advanced settings', '추가 설정 펼치기': 'Show advanced settings', '고정 해제': 'Unpin', '상단 고정': 'Pin to top', '수정': 'Edit', '메인 카운터는 하나 이상 필요합니다': 'At least one main counter is required',
    '문구 미리보기': 'Caption preview', '이미지를 열 수 없습니다.': 'Could not open the image.', '합성할 사진을 선택해 주세요.': 'Choose photos to combine.', '사진은 한 장에 최대 9개까지 담을 수 있습니다.': 'You can include up to 9 photos in one image.', '합성 이미지를 만들 수 없습니다.': 'Could not create the composite image.', '사진이 너무 많아 한 장에 배치할 수 없습니다. 사진을 줄여 주세요.': 'There are too many photos for one image. Remove some photos and try again.', '합성 이미지를 저장하지 못했습니다.': 'Could not save the composite image.', '이미지 만드는 중…': 'Creating image…', '이미지 만들기': 'Create image', '뜨개 기록': 'Knitting journal', '한 코씩 완성해 가는 시간': 'One stitch at a time', '작업 과정': 'In progress', '뜨개 프로젝트': 'Knitting project',
    '프로젝트 정보': 'Project details', '도안 정보': 'Pattern details', '사용한 실': 'Yarn used', '바늘 · 부자재': 'Needles & accessories', '게이지 · 손땀': 'Gauge & tension', '사이즈 · 변형': 'Size & modifications', '작업 과정 기록': 'Progress notes', '완성 기록': 'Finishing notes', '뜨개 종류': 'Craft', '상태': 'Status', 'CO (시작일)': 'Cast on (start date)', 'FO (완성일)': 'Bind off (finish date)', '만든 대상': 'Made for', '원작자 · 디자이너': 'Designer', '도안 출처': 'Pattern source', '도안 구매처': 'Pattern purchased from', '도안 링크': 'Pattern link', '사용 언어': 'Pattern language', '원본 사이즈': 'Original sizes', '선택 사이즈': 'Selected size', '디자인 특징': 'Design details', '도안 메모': 'Pattern notes', '브랜드': 'Brand', '제품명': 'Product', '색상명': 'Color name', '색상번호': 'Color number', '성분': 'Fiber content', '제조국': 'Country of origin', '두께': 'Yarn weight', '권장 바늘': 'Recommended needles', '한 타래 중량': 'Skein weight', '한 타래 길이': 'Skein length', '구매처': 'Purchased from', '구매 링크': 'Purchase link', '구매 가격': 'Price', '구매 수량': 'Quantity purchased', '사용 타래 수': 'Skeins used', '사용 중량': 'Weight used', '사용 길이': 'Length used', '남은 실': 'Leftover yarn', '구간': 'Section', '바늘 종류': 'Needle type', '사이즈': 'Size', '케이블 길이': 'Cable length', '종류': 'Type', '수량': 'Quantity', '상세': 'Details', '측정 기준': 'Measured over', '도안 게이지': 'Pattern gauge', '세탁 전 게이지': 'Before washing', '세탁 후 게이지': 'After washing', '많이 널손': 'Very loose', '널손': 'Loose', '쫀손': 'Tight', '많이 쫀손': 'Very tight', '원본(도안)': 'Original (pattern)', '변경 내용': 'Changes', '변형': 'Modification', '작업 기록': 'Progress note', '세탁 여부': 'Washed', '세탁 방법': 'Washing method', '블로킹 방법': 'Blocking method', '세탁 전 크기': 'Size before washing', '세탁 후 크기': 'Size after washing', '세탁·블로킹 변화': 'Washing and blocking notes', '난이도': 'Difficulty', '전체 만족도': 'Overall satisfaction', '실 만족도': 'Yarn satisfaction', '도안 만족도': 'Pattern satisfaction', '다시 뜰 의향': 'Would make again', '문제와 해결': 'Problems and solutions', '다음에 바꾸고 싶은 점': 'Changes for next time', '완성 메모': 'Finishing notes', '기장': 'Length', '가슴둘레': 'Bust circumference', '소매길이': 'Sleeve length', '항목': 'Item', '실': 'Yarn', '대표 사진': 'Cover photo', '날짜 미설정': 'No date set', '설명 없음': 'No description',
    '분명 셌는데… 다시 셀게요.': 'I definitely counted that… Let me count again.', '도안보고, 뜨고, 또 도안보고.': 'Check the pattern, knit, repeat.', '한 코씩 불러오는 중…': 'Loading one stitch at a time…', '몇 단이었지… 다시 세는 중.': 'Which row was I on? Counting again…', '한 코가 어디 갔지?': 'Where did that stitch go?', '푸를까… 그냥 갈까…': 'Should I unravel it… or keep going?', '실은 충분합니다. 아마도.': 'There should be enough yarn. Probably.', '잠깐, 지금 겉뜨기였나?': 'Wait, was that a knit stitch?', '블로킹이 해결해 줄 거예요.': 'Blocking will fix it.', '도안 해독 중…': 'Deciphering the pattern…',
    '대바늘': 'Knitting', '코바늘': 'Crochet', '예정': 'Planned', '진행중': 'In progress', '중단': 'Paused', '라글란': 'Raglan', '드롭숄더': 'Drop shoulder', '브이넥': 'V-neck', '크롭': 'Cropped', '오버핏': 'Oversized', '케이블': 'Cable', '배색': 'Colorwork', '탑다운': 'Top-down', '바텀업': 'Bottom-up', '작게 느껴짐': 'Feels small', '딱 맞음': 'Just right', '여유 있음': 'Relaxed fit', '많이 여유 있음': 'Very roomy', '쉬움': 'Easy', '어려움': 'Difficult', '있음': 'Yes', '아니오': 'No', '실제': 'Actual',
  },
  ja: {
    '홈': 'ホーム', '프로젝트': 'プロジェクト', '보고서': 'レポート', '프로젝트 불러오는 중…': 'プロジェクトを読み込み中…', '프로젝트를 찾을 수 없습니다.': 'プロジェクトが見つかりません。', '프로젝트를 저장하지 못했습니다.': 'プロジェクトを保存できませんでした。', '프로젝트를 불러오지 못했습니다.': 'プロジェクトを読み込めませんでした。', '프로젝트를 보관했습니다.': 'プロジェクトをアーカイブしました。', '프로젝트 보관을 해제했습니다.': 'アーカイブを解除しました。', '프로젝트를 휴지통으로 이동했습니다.': 'プロジェクトをゴミ箱に移動しました。', '프로젝트를 휴지통으로 옮겼습니다.': 'プロジェクトをゴミ箱に移動しました。', '프로젝트와 연결된 모든 작업·보고서를 영구 삭제할까요? 이 작업은 되돌릴 수 없습니다.': 'プロジェクトと関連する作業・レポートをすべて完全に削除しますか？この操作は取り消せません。', '프로젝트를 휴지통으로 이동할까요? 작업과 보고서는 보관되며 휴지통에서 복구할 수 있습니다.': 'プロジェクトをゴミ箱に移動しますか？作業とレポートは保持され、ゴミ箱から復元できます。', '뜨개 차트': '編み物チャート', '사진 도안': '写真の編み図', 'PDF 도안': 'PDF編み図', '정보 저장': '詳細を保存', '보관 해제': 'アーカイブ解除', '변경을 되돌렸습니다.': '変更を元に戻しました。', '저장 중': '保存中', '사진 바꾸기': '写真を変更', '크게 보기': '拡大表示', '무늬단': '模様の段', '메인 카운터 추가': 'メインカウンターを追加', '추가 설정 접기': '詳細設定を閉じる', '추가 설정 펼치기': '詳細設定を開く', '고정 해제': '固定を解除', '상단 고정': '上部に固定', '수정': '編集', '메인 카운터는 하나 이상 필요합니다': 'メインカウンターを1つ以上設定してください',
    '문구 미리보기': 'キャプションのプレビュー', '이미지를 열 수 없습니다.': '画像を開けませんでした。', '합성할 사진을 선택해 주세요.': '合成する写真を選択してください。', '사진은 한 장에 최대 9개까지 담을 수 있습니다.': '1枚の画像に最大9枚の写真を含められます。', '합성 이미지를 만들 수 없습니다.': '合成画像を作成できませんでした。', '사진이 너무 많아 한 장에 배치할 수 없습니다. 사진을 줄여 주세요.': '写真が多すぎて1枚に配置できません。写真を減らしてください。', '합성 이미지를 저장하지 못했습니다.': '合成画像を保存できませんでした。', '이미지 만드는 중…': '画像を作成中…', '이미지 만들기': '画像を作成', '뜨개 기록': '編み物日記', '한 코씩 완성해 가는 시간': '一目ずつ完成に近づく時間', '작업 과정': '制作過程', '뜨개 프로젝트': '編み物プロジェクト',
    '프로젝트 정보': 'プロジェクト情報', '도안 정보': '編み図情報', '사용한 실': '使用した糸', '바늘 · 부자재': '針・道具', '게이지 · 손땀': 'ゲージ・手加減', '사이즈 · 변형': 'サイズ・変更', '작업 과정 기록': '制作記録', '완성 기록': '完成記録', '뜨개 종류': '編み物の種類', '상태': '状態', 'CO (시작일)': '作り目 (開始日)', 'FO (완성일)': '伏せ止め (完成日)', '만든 대상': '作った相手', '원작자 · 디자이너': 'デザイナー', '도안 출처': '編み図の出典', '도안 구매처': '編み図の購入先', '도안 링크': '編み図リンク', '사용 언어': '使用言語', '원본 사이즈': '元のサイズ', '선택 사이즈': '選択サイズ', '디자인 특징': 'デザインの特徴', '도안 메모': '編み図メモ', '브랜드': 'ブランド', '제품명': '商品名', '색상명': '色名', '색상번호': '色番号', '성분': '素材', '제조국': '製造国', '두께': '糸の太さ', '권장 바늘': '推奨針', '한 타래 중량': '1玉の重量', '한 타래 길이': '1玉の長さ', '구매처': '購入先', '구매 링크': '購入リンク', '구매 가격': '購入価格', '구매 수량': '購入数', '사용 타래 수': '使用玉数', '사용 중량': '使用重量', '사용 길이': '使用長さ', '남은 실': '残り糸', '구간': '区分', '바늘 종류': '針の種類', '사이즈': 'サイズ', '케이블 길이': 'コードの長さ', '종류': '種類', '수량': '数量', '상세': '詳細', '측정 기준': '測定基準', '도안 게이지': '編み図のゲージ', '세탁 전 게이지': '洗濯前のゲージ', '세탁 후 게이지': '洗濯後のゲージ', '많이 널손': 'かなりゆるめ', '널손': 'ゆるめ', '쫀손': 'きつめ', '많이 쫀손': 'かなりきつめ', '원본(도안)': '元の編み図', '변경 내용': '変更内容', '변형': '変更', '작업 기록': '作業記録', '세탁 여부': '洗濯した', '세탁 방법': '洗濯方法', '블로킹 방법': 'ブロッキング方法', '세탁 전 크기': '洗濯前のサイズ', '세탁 후 크기': '洗濯後のサイズ', '세탁·블로킹 변화': '洗濯・ブロッキングの変化', '난이도': '難易度', '전체 만족도': '全体の満足度', '실 만족도': '糸の満足度', '도안 만족도': '編み図の満足度', '다시 뜰 의향': 'また編みたい', '문제와 해결': '問題と解決方法', '다음에 바꾸고 싶은 점': '次回変えたい点', '완성 메모': '完成メモ', '기장': '着丈', '가슴둘레': '胸囲', '소매길이': '袖丈', '항목': '項目', '실': '糸', '대표 사진': '代表写真', '날짜 미설정': '日付未設定', '설명 없음': '説明なし',
    '분명 셌는데… 다시 셀게요.': '数えたはずなのに…もう一度数えます。', '도안보고, 뜨고, 또 도안보고.': '編み図を見て、編んで、また編み図を見る。', '한 코씩 불러오는 중…': '一目ずつ読み込み中…', '몇 단이었지… 다시 세는 중.': '何段目だったかな…数え直しています。', '한 코가 어디 갔지?': 'あの目はどこへ？', '푸를까… 그냥 갈까…': 'ほどこうか…このまま進もうか…', '실은 충분합니다. 아마도.': '糸は足りるはず。たぶん。', '잠깐, 지금 겉뜨기였나?': '待って、今は表編みだった？', '블로킹이 해결해 줄 거예요.': 'ブロッキングが何とかしてくれます。', '도안 해독 중…': '編み図を解読中…',
    '대바늘': '棒針', '코바늘': 'かぎ針', '예정': '予定', '진행중': '進行中', '중단': '中断', '라글란': 'ラグラン', '드롭숄더': 'ドロップショルダー', '브이넥': 'Vネック', '크롭': 'クロップド', '오버핏': 'オーバーサイズ', '케이블': 'ケーブル', '배색': '配色', '탑다운': 'トップダウン', '바텀업': 'ボトムアップ', '작게 느껴짐': '小さく感じる', '딱 맞음': 'ちょうどよい', '여유 있음': 'ゆったり', '많이 여유 있음': 'かなりゆったり', '쉬움': '簡単', '어려움': '難しい', '있음': 'あり', '아니오': 'いいえ', '실제': '実測',
  },
  de: {
    '홈': 'Startseite', '프로젝트': 'Projekte', '보고서': 'Berichte', '프로젝트 불러오는 중…': 'Projekt wird geladen…', '프로젝트를 찾을 수 없습니다.': 'Projekt nicht gefunden.', '프로젝트를 저장하지 못했습니다.': 'Projekt konnte nicht gespeichert werden.', '프로젝트를 불러오지 못했습니다.': 'Projekt konnte nicht geladen werden.', '프로젝트를 보관했습니다.': 'Projekt archiviert.', '프로젝트 보관을 해제했습니다.': 'Archivierung aufgehoben.', '프로젝트를 휴지통으로 이동했습니다.': 'Projekt in den Papierkorb verschoben.', '프로젝트를 휴지통으로 옮겼습니다.': 'Projekt in den Papierkorb verschoben.', '프로젝트와 연결된 모든 작업·보고서를 영구 삭제할까요? 이 작업은 되돌릴 수 없습니다.': 'Dieses Projekt und alle zugehörigen Arbeiten und Berichte endgültig löschen? Dieser Vorgang kann nicht rückgängig gemacht werden.', '프로젝트를 휴지통으로 이동할까요? 작업과 보고서는 보관되며 휴지통에서 복구할 수 있습니다.': 'Dieses Projekt in den Papierkorb verschieben? Arbeit und Berichte bleiben erhalten und können wiederhergestellt werden.', '뜨개 차트': 'Strickdiagramm', '사진 도안': 'Fotovorlage', 'PDF 도안': 'PDF-Anleitung', '정보 저장': 'Details speichern', '보관 해제': 'Archivierung aufheben', '변경을 되돌렸습니다.': 'Änderung rückgängig gemacht.', '저장 중': 'Wird gespeichert', '사진 바꾸기': 'Foto ändern', '크게 보기': 'Größer anzeigen', '무늬단': 'Musterrunde', '메인 카운터 추가': 'Hauptzähler hinzufügen', '추가 설정 접기': 'Erweiterte Einstellungen ausblenden', '추가 설정 펼치기': 'Erweiterte Einstellungen anzeigen', '고정 해제': 'Lösen', '상단 고정': 'Oben anheften', '수정': 'Bearbeiten', '메인 카운터는 하나 이상 필요합니다': 'Es ist mindestens ein Hauptzähler erforderlich',
    '문구 미리보기': 'Textvorschau', '이미지를 열 수 없습니다.': 'Bild konnte nicht geöffnet werden.', '합성할 사진을 선택해 주세요.': 'Wähle Fotos für die Collage aus.', '사진은 한 장에 최대 9개까지 담을 수 있습니다.': 'Ein Bild kann höchstens 9 Fotos enthalten.', '합성 이미지를 만들 수 없습니다.': 'Collage konnte nicht erstellt werden.', '사진이 너무 많아 한 장에 배치할 수 없습니다. 사진을 줄여 주세요.': 'Zu viele Fotos für ein Bild. Entferne einige Fotos und versuche es erneut.', '합성 이미지를 저장하지 못했습니다.': 'Collage konnte nicht gespeichert werden.', '이미지 만드는 중…': 'Bild wird erstellt…', '이미지 만들기': 'Bild erstellen', '뜨개 기록': 'Stricktagebuch', '한 코씩 완성해 가는 시간': 'Schritt für Schritt zum fertigen Strickstück', '작업 과정': 'Arbeitsfortschritt', '뜨개 프로젝트': 'Strickprojekt',
    '프로젝트 정보': 'Projektinformationen', '도안 정보': 'Anleitungsdetails', '사용한 실': 'Verwendetes Garn', '바늘 · 부자재': 'Nadeln und Zubehör', '게이지 · 손땀': 'Maschenprobe und Spannung', '사이즈 · 변형': 'Größe und Änderungen', '작업 과정 기록': 'Fortschrittsnotizen', '완성 기록': 'Fertigstellung', '뜨개 종류': 'Handarbeit', '상태': 'Status', 'CO (시작일)': 'Anschlag (Startdatum)', 'FO (완성일)': 'Abketten (Fertigstellungsdatum)', '만든 대상': 'Für wen', '원작자 · 디자이너': 'Designer', '도안 출처': 'Anleitungsquelle', '도안 구매처': 'Anleitung gekauft bei', '도안 링크': 'Anleitungslink', '사용 언어': 'Sprache der Anleitung', '원본 사이즈': 'Originalgrößen', '선택 사이즈': 'Ausgewählte Größe', '디자인 특징': 'Designmerkmale', '도안 메모': 'Notizen zur Anleitung', '브랜드': 'Marke', '제품명': 'Produkt', '색상명': 'Farbname', '색상번호': 'Farbnummer', '성분': 'Faserzusammensetzung', '제조국': 'Herstellungsland', '두께': 'Garnstärke', '권장 바늘': 'Empfohlene Nadeln', '한 타래 중량': 'Knäuelgewicht', '한 타래 길이': 'Lauflänge pro Knäuel', '구매처': 'Gekauft bei', '구매 링크': 'Kauflink', '구매 가격': 'Kaufpreis', '구매 수량': 'Kaufmenge', '사용 타래 수': 'Verbrauchte Knäuel', '사용 중량': 'Verbrauchtes Gewicht', '사용 길이': 'Verbrauchte Länge', '남은 실': 'Garnrest', '구간': 'Abschnitt', '바늘 종류': 'Nadeltyp', '사이즈': 'Größe', '케이블 길이': 'Seillänge', '종류': 'Typ', '수량': 'Menge', '상세': 'Details', '측정 기준': 'Messgrundlage', '도안 게이지': 'Maschenprobe laut Anleitung', '세탁 전 게이지': 'Vor dem Waschen', '세탁 후 게이지': 'Nach dem Waschen', '많이 널손': 'Sehr locker', '널손': 'Locker', '쫀손': 'Fest', '많이 쫀손': 'Sehr fest', '원본(도안)': 'Original (Anleitung)', '변경 내용': 'Änderungen', '변형': 'Anpassung', '작업 기록': 'Arbeitsnotiz', '세탁 여부': 'Gewaschen', '세탁 방법': 'Waschmethode', '블로킹 방법': 'Spannmethode', '세탁 전 크기': 'Maße vor dem Waschen', '세탁 후 크기': 'Maße nach dem Waschen', '세탁·블로킹 변화': 'Änderungen durch Waschen und Spannen', '난이도': 'Schwierigkeit', '전체 만족도': 'Gesamtzufriedenheit', '실 만족도': 'Garnzufriedenheit', '도안 만족도': 'Zufriedenheit mit der Anleitung', '다시 뜰 의향': 'Würde ich erneut stricken', '문제와 해결': 'Probleme und Lösungen', '다음에 바꾸고 싶은 점': 'Was ich nächstes Mal ändern möchte', '완성 메모': 'Notizen zum fertigen Stück', '기장': 'Länge', '가슴둘레': 'Brustumfang', '소매길이': 'Ärmellänge', '항목': 'Punkt', '실': 'Garn', '대표 사진': 'Titelbild', '날짜 미설정': 'Kein Datum festgelegt', '설명 없음': 'Keine Beschreibung',
    '분명 셌는데… 다시 셀게요.': 'Das habe ich doch gezählt… ich zähle noch einmal.', '도안보고, 뜨고, 또 도안보고.': 'Anleitung ansehen, stricken, wieder ansehen.', '한 코씩 불러오는 중…': 'Masche für Masche wird geladen…', '몇 단이었지… 다시 세는 중.': 'Welche Reihe war das? Ich zähle noch einmal…', '한 코가 어디 갔지?': 'Wo ist diese Masche hin?', '푸를까… 그냥 갈까…': 'Aufribbeln… oder weitermachen?', '실은 충분합니다. 아마도.': 'Das Garn reicht. Wahrscheinlich.', '잠깐, 지금 겉뜨기였나?': 'Moment, war das gerade eine rechte Masche?', '블로킹이 해결해 줄 거예요.': 'Das Spannen wird es richten.', '도안 해독 중…': 'Die Anleitung wird entschlüsselt…',
    '대바늘': 'Stricken', '코바늘': 'Häkeln', '예정': 'Geplant', '진행중': 'In Arbeit', '중단': 'Pausiert', '라글란': 'Raglan', '드롭숄더': 'Überschnittene Schulter', '브이넥': 'V-Ausschnitt', '크롭': 'Kurz geschnitten', '오버핏': 'Oversize', '케이블': 'Zopfmuster', '배색': 'Farbmuster', '탑다운': 'Top-down', '바텀업': 'Bottom-up', '작게 느껴짐': 'Fühlt sich zu klein an', '딱 맞음': 'Passt genau', '여유 있음': 'Locker', '많이 여유 있음': 'Sehr locker', '쉬움': 'Einfach', '어려움': 'Schwierig', '있음': 'Ja', '아니오': 'Nein', '실제': 'Tatsächlich',
  },
  da: {
    '홈': 'Hjem', '프로젝트': 'Projekter', '보고서': 'Rapporter', '프로젝트 불러오는 중…': 'Indlæser projekt…', '프로젝트를 찾을 수 없습니다.': 'Projektet blev ikke fundet.', '프로젝트를 저장하지 못했습니다.': 'Projektet kunne ikke gemmes.', '프로젝트를 불러오지 못했습니다.': 'Projektet kunne ikke indlæses.', '프로젝트를 보관했습니다.': 'Projekt arkiveret.', '프로젝트 보관을 해제했습니다.': 'Arkivering ophævet.', '프로젝트를 휴지통으로 이동했습니다.': 'Projekt flyttet til papirkurven.', '프로젝트를 휴지통으로 옮겼습니다.': 'Projekt flyttet til papirkurven.', '프로젝트와 연결된 모든 작업·보고서를 영구 삭제할까요? 이 작업은 되돌릴 수 없습니다.': 'Vil du slette projektet og alle tilknyttede arbejder og rapporter permanent? Dette kan ikke fortrydes.', '프로젝트를 휴지통으로 이동할까요? 작업과 보고서는 보관되며 휴지통에서 복구할 수 있습니다.': 'Flyt projektet til papirkurven? Arbejde og rapporter gemmes og kan gendannes fra papirkurven.', '뜨개 차트': 'Strikkediagram', '사진 도안': 'Fotoopskrift', 'PDF 도안': 'PDF-opskrift', '정보 저장': 'Gem oplysninger', '보관 해제': 'Ophæv arkivering', '변경을 되돌렸습니다.': 'Ændringen er fortrudt.', '저장 중': 'Gemmer', '사진 바꾸기': 'Skift foto', '크게 보기': 'Vis større', '무늬단': 'Mønsterrække', '메인 카운터 추가': 'Tilføj hovedtæller', '추가 설정 접기': 'Skjul avancerede indstillinger', '추가 설정 펼치기': 'Vis avancerede indstillinger', '고정 해제': 'Frigør', '상단 고정': 'Fastgør øverst', '수정': 'Rediger', '메인 카운터는 하나 이상 필요합니다': 'Der skal være mindst én hovedtæller',
    '문구 미리보기': 'Forhåndsvisning af tekst', '이미지를 열 수 없습니다.': 'Billedet kunne ikke åbnes.', '합성할 사진을 선택해 주세요.': 'Vælg fotos, der skal sammensættes.', '사진은 한 장에 최대 9개까지 담을 수 있습니다.': 'Et billede kan indeholde højst 9 fotos.', '합성 이미지를 만들 수 없습니다.': 'Det sammensatte billede kunne ikke oprettes.', '사진이 너무 많아 한 장에 배치할 수 없습니다. 사진을 줄여 주세요.': 'Der er for mange fotos til ét billede. Fjern nogle fotos, og prøv igen.', '합성 이미지를 저장하지 못했습니다.': 'Det sammensatte billede kunne ikke gemmes.', '이미지 만드는 중…': 'Opretter billede…', '이미지 만들기': 'Opret billede', '뜨개 기록': 'Strikkedagbog', '한 코씩 완성해 가는 시간': 'Tid, hvor arbejdet vokser maske for maske', '작업 과정': 'Arbejdsforløb', '뜨개 프로젝트': 'Strikkeprojekt',
    '프로젝트 정보': 'Projektoplysninger', '도안 정보': 'Opskriftsoplysninger', '사용한 실': 'Brugt garn', '바늘 · 부자재': 'Pinde og tilbehør', '게이지 · 손땀': 'Strikkefasthed og spænding', '사이즈 · 변형': 'Størrelse og ændringer', '작업 과정 기록': 'Noter om forløbet', '완성 기록': 'Færdiggørelse', '뜨개 종류': 'Håndarbejde', '상태': 'Status', 'CO (시작일)': 'Slå op (startdato)', 'FO (완성일)': 'Luk af (færdigdato)', '만든 대상': 'Lavet til', '원작자 · 디자이너': 'Designer', '도안 출처': 'Opskriftens kilde', '도안 구매처': 'Opskrift købt hos', '도안 링크': 'Link til opskrift', '사용 언어': 'Opskriftens sprog', '원본 사이즈': 'Originale størrelser', '선택 사이즈': 'Valgt størrelse', '디자인 특징': 'Designtræk', '도안 메모': 'Opskriftsnoter', '브랜드': 'Mærke', '제품명': 'Produkt', '색상명': 'Farvenavn', '색상번호': 'Farvenummer', '성분': 'Fiberindhold', '제조국': 'Produktionsland', '두께': 'Garntykkelse', '권장 바늘': 'Anbefalede pinde', '한 타래 중량': 'Nøglens vægt', '한 타래 길이': 'Længde pr. nøgle', '구매처': 'Købt hos', '구매 링크': 'Købslink', '구매 가격': 'Købspris', '구매 수량': 'Købt antal', '사용 타래 수': 'Brugte nøgler', '사용 중량': 'Brugt vægt', '사용 길이': 'Brugt længde', '남은 실': 'Restgarn', '구간': 'Afsnit', '바늘 종류': 'Pindetype', '사이즈': 'Størrelse', '케이블 길이': 'Kabellængde', '종류': 'Type', '수량': 'Antal', '상세': 'Detaljer', '측정 기준': 'Målt over', '도안 게이지': 'Opskriftens strikkefasthed', '세탁 전 게이지': 'Før vask', '세탁 후 게이지': 'Efter vask', '많이 널손': 'Meget løst', '널손': 'Løst', '쫀손': 'Fast', '많이 쫀손': 'Meget fast', '원본(도안)': 'Original (opskrift)', '변경 내용': 'Ændringer', '변형': 'Tilpasning', '작업 기록': 'Arbejdsnote', '세탁 여부': 'Vasket', '세탁 방법': 'Vaskemetode', '블로킹 방법': 'Blokeringsmetode', '세탁 전 크기': 'Mål før vask', '세탁 후 크기': 'Mål efter vask', '세탁·블로킹 변화': 'Ændringer efter vask og blokning', '난이도': 'Sværhedsgrad', '전체 만족도': 'Samlet tilfredshed', '실 만족도': 'Garnets kvalitet', '도안 만족도': 'Opskriftens kvalitet', '다시 뜰 의향': 'Vil strikke den igen', '문제와 해결': 'Problemer og løsninger', '다음에 바꾸고 싶은 점': 'Ændringer næste gang', '완성 메모': 'Noter til det færdige arbejde', '기장': 'Længde', '가슴둘레': 'Brystmål', '소매길이': 'Ærmelængde', '항목': 'Punkt', '실': 'Garn', '대표 사진': 'Forsidefoto', '날짜 미설정': 'Ingen dato valgt', '설명 없음': 'Ingen beskrivelse',
    '분명 셌는데… 다시 셀게요.': 'Jeg talte dem da… jeg tæller igen.', '도안보고, 뜨고, 또 도안보고.': 'Se opskriften, strik, se opskriften igen.', '한 코씩 불러오는 중…': 'Indlæser maske for maske…', '몇 단이었지… 다시 세는 중.': 'Hvilken pind var jeg nået til? Tæller igen…', '한 코가 어디 갔지?': 'Hvor blev den maske af?', '푸를까… 그냥 갈까…': 'Skal jeg trævle op… eller fortsætte?', '실은 충분합니다. 아마도.': 'Der er garn nok. Forhåbentlig.', '잠깐, 지금 겉뜨기였나?': 'Vent, var det en retmaske?', '블로킹이 해결해 줄 거예요.': 'Blokning skal nok hjælpe.', '도안 해독 중…': 'Tyder opskriften…',
    '대바늘': 'Strikning', '코바늘': 'Hækling', '예정': 'Planlagt', '진행중': 'I gang', '중단': 'Sat på pause', '라글란': 'Raglan', '드롭숄더': 'Nedsænket skulder', '브이넥': 'V-hals', '크롭': 'Kort model', '오버핏': 'Oversized', '케이블': 'Snoning', '배색': 'Farvestrik', '탑다운': 'Oppefra og ned', '바텀업': 'Nedefra og op', '작게 느껴짐': 'Føles for lille', '딱 맞음': 'Passer præcist', '여유 있음': 'Løs pasform', '많이 여유 있음': 'Meget rummelig', '쉬움': 'Let', '어려움': 'Svær', '있음': 'Ja', '아니오': 'Nej', '실제': 'Faktisk',
  },
  nb: {
    '홈': 'Hjem', '프로젝트': 'Prosjekter', '보고서': 'Rapporter', '프로젝트 불러오는 중…': 'Laster prosjekt…', '프로젝트를 찾을 수 없습니다.': 'Fant ikke prosjektet.', '프로젝트를 저장하지 못했습니다.': 'Kunne ikke lagre prosjektet.', '프로젝트를 불러오지 못했습니다.': 'Kunne ikke laste prosjektet.', '프로젝트를 보관했습니다.': 'Prosjektet er arkivert.', '프로젝트 보관을 해제했습니다.': 'Arkivering opphevet.', '프로젝트를 휴지통으로 이동했습니다.': 'Prosjektet er flyttet til papirkurven.', '프로젝트를 휴지통으로 옮겼습니다.': 'Prosjektet er flyttet til papirkurven.', '프로젝트와 연결된 모든 작업·보고서를 영구 삭제할까요? 이 작업은 되돌릴 수 없습니다.': 'Slette prosjektet og alle tilknyttede arbeider og rapporter permanent? Dette kan ikke angres.', '프로젝트를 휴지통으로 이동할까요? 작업과 보고서는 보관되며 휴지통에서 복구할 수 있습니다.': 'Flytte prosjektet til papirkurven? Arbeid og rapporter beholdes og kan gjenopprettes fra papirkurven.', '뜨개 차트': 'Strikkediagram', '사진 도안': 'Fotooppskrift', 'PDF 도안': 'PDF-oppskrift', '정보 저장': 'Lagre detaljer', '보관 해제': 'Opphev arkivering', '변경을 되돌렸습니다.': 'Endringen er angret.', '저장 중': 'Lagrer', '사진 바꾸기': 'Bytt bilde', '크게 보기': 'Vis større', '무늬단': 'Mønsterrad', '메인 카운터 추가': 'Legg til hovedteller', '추가 설정 접기': 'Skjul avanserte innstillinger', '추가 설정 펼치기': 'Vis avanserte innstillinger', '고정 해제': 'Løsne', '상단 고정': 'Fest øverst', '수정': 'Rediger', '메인 카운터는 하나 이상 필요합니다': 'Minst én hovedteller kreves',
    '문구 미리보기': 'Forhåndsvisning av tekst', '이미지를 열 수 없습니다.': 'Kunne ikke åpne bildet.', '합성할 사진을 선택해 주세요.': 'Velg bilder som skal settes sammen.', '사진은 한 장에 최대 9개까지 담을 수 있습니다.': 'Ett bilde kan inneholde opptil 9 bilder.', '합성 이미지를 만들 수 없습니다.': 'Kunne ikke lage det sammensatte bildet.', '사진이 너무 많아 한 장에 배치할 수 없습니다. 사진을 줄여 주세요.': 'Det er for mange bilder for ett bilde. Fjern noen bilder og prøv igjen.', '합성 이미지를 저장하지 못했습니다.': 'Kunne ikke lagre det sammensatte bildet.', '이미지 만드는 중…': 'Lager bilde…', '이미지 만들기': 'Lag bilde', '뜨개 기록': 'Strikkedagbok', '한 코씩 완성해 가는 시간': 'Tiden det tar å fullføre én maske om gangen', '작업 과정': 'Arbeidsprosess', '뜨개 프로젝트': 'Strikkeprosjekt',
    '프로젝트 정보': 'Prosjektinformasjon', '도안 정보': 'Oppskriftsinformasjon', '사용한 실': 'Brukt garn', '바늘 · 부자재': 'Pinner og tilbehør', '게이지 · 손땀': 'Strikkefasthet og håndlag', '사이즈 · 변형': 'Størrelse og endringer', '작업 과정 기록': 'Arbeidsnotater', '완성 기록': 'Ferdigstilling', '뜨개 종류': 'Håndarbeidstype', '상태': 'Status', 'CO (시작일)': 'Legg opp (startdato)', 'FO (완성일)': 'Fell av (ferdigdato)', '만든 대상': 'Laget til', '원작자 · 디자이너': 'Designer', '도안 출처': 'Oppskriftskilde', '도안 구매처': 'Oppskrift kjøpt hos', '도안 링크': 'Oppskriftslenke', '사용 언어': 'Oppskriftsspråk', '원본 사이즈': 'Opprinnelige størrelser', '선택 사이즈': 'Valgt størrelse', '디자인 특징': 'Designdetaljer', '도안 메모': 'Oppskriftsnotater', '브랜드': 'Merke', '제품명': 'Produkt', '색상명': 'Fargenavn', '색상번호': 'Fargenummer', '성분': 'Fiberinnhold', '제조국': 'Produksjonsland', '두께': 'Garntykkelse', '권장 바늘': 'Anbefalte pinner', '한 타래 중량': 'Nøstevekt', '한 타래 길이': 'Lengde per nøste', '구매처': 'Kjøpt hos', '구매 링크': 'Kjøpslenke', '구매 가격': 'Kjøpspris', '구매 수량': 'Antall kjøpt', '사용 타래 수': 'Brukte nøster', '사용 중량': 'Brukt vekt', '사용 길이': 'Brukt lengde', '남은 실': 'Restegarn', '구간': 'Del', '바늘 종류': 'Pinnetype', '사이즈': 'Størrelse', '케이블 길이': 'Kabellengde', '종류': 'Type', '수량': 'Antall', '상세': 'Detaljer', '측정 기준': 'Målt over', '도안 게이지': 'Oppskriftens strikkefasthet', '세탁 전 게이지': 'Før vask', '세탁 후 게이지': 'Etter vask', '많이 널손': 'Svært løst', '널손': 'Løst', '쫀손': 'Fast', '많이 쫀손': 'Svært fast', '원본(도안)': 'Original (oppskrift)', '변경 내용': 'Endringer', '변형': 'Tilpasning', '작업 기록': 'Arbeidsnotat', '세탁 여부': 'Vasket', '세탁 방법': 'Vaskemetode', '블로킹 방법': 'Blokking', '세탁 전 크기': 'Mål før vask', '세탁 후 크기': 'Mål etter vask', '세탁·블로킹 변화': 'Endringer etter vask og blokking', '난이도': 'Vanskelighetsgrad', '전체 만족도': 'Samlet tilfredshet', '실 만족도': 'Garnvurdering', '도안 만족도': 'Oppskriftsvurdering', '다시 뜰 의향': 'Vil strikke igjen', '문제와 해결': 'Problemer og løsninger', '다음에 바꾸고 싶은 점': 'Endringer neste gang', '완성 메모': 'Notater om det ferdige arbeidet', '기장': 'Lengde', '가슴둘레': 'Brystmål', '소매길이': 'Ermelengde', '항목': 'Punkt', '실': 'Garn', '대표 사진': 'Forsidebilde', '날짜 미설정': 'Ingen dato valgt', '설명 없음': 'Ingen beskrivelse',
    '분명 셌는데… 다시 셀게요.': 'Jeg telte dem jo… jeg teller igjen.', '도안보고, 뜨고, 또 도안보고.': 'Se på oppskriften, strikk, se igjen.', '한 코씩 불러오는 중…': 'Laster inn én maske om gangen…', '몇 단이었지… 다시 세는 중.': 'Hvilken omgang var jeg på? Teller igjen…', '한 코가 어디 갔지?': 'Hvor ble det av den masken?', '푸를까… 그냥 갈까…': 'Skal jeg rekke opp… eller fortsette?', '실은 충분합니다. 아마도.': 'Det er nok garn. Sannsynligvis.', '잠깐, 지금 겉뜨기였나?': 'Vent, var det en rettmaske?', '블로킹이 해결해 줄 거예요.': 'Blokking ordner det.', '도안 해독 중…': 'Tyding av oppskriften…',
    '대바늘': 'Strikking', '코바늘': 'Hekling', '예정': 'Planlagt', '진행중': 'Pågår', '중단': 'Satt på pause', '라글란': 'Raglan', '드롭숄더': 'Nedsenket skulder', '브이넥': 'V-hals', '크롭': 'Kort modell', '오버핏': 'Oversized', '케이블': 'Flettemønster', '배색': 'Fargestrikk', '탑다운': 'Ovenfra og ned', '바텀업': 'Nedenfra og opp', '작게 느껴짐': 'Føles for liten', '딱 맞음': 'Passer akkurat', '여유 있음': 'Ledig passform', '많이 여유 있음': 'Svært romslig', '쉬움': 'Lett', '어려움': 'Vanskelig', '있음': 'Ja', '아니오': 'Nei', '실제': 'Faktisk',
  },
  fi: {
    '홈': 'Etusivu', '프로젝트': 'Projektit', '보고서': 'Raportit', '프로젝트 불러오는 중…': 'Ladataan projektia…', '프로젝트를 찾을 수 없습니다.': 'Projektia ei löytynyt.', '프로젝트를 저장하지 못했습니다.': 'Projektia ei voitu tallentaa.', '프로젝트를 불러오지 못했습니다.': 'Projektia ei voitu ladata.', '프로젝트를 보관했습니다.': 'Projekti arkistoitu.', '프로젝트 보관을 해제했습니다.': 'Arkistointi peruutettu.', '프로젝트를 휴지통으로 이동했습니다.': 'Projekti siirrettiin roskakoriin.', '프로젝트를 휴지통으로 옮겼습니다.': 'Projekti siirrettiin roskakoriin.', '프로젝트와 연결된 모든 작업·보고서를 영구 삭제할까요? 이 작업은 되돌릴 수 없습니다.': 'Poistetaanko projekti ja kaikki siihen liittyvät työt ja raportit pysyvästi? Tätä ei voi kumota.', '프로젝트를 휴지통으로 이동할까요? 작업과 보고서는 보관되며 휴지통에서 복구할 수 있습니다.': 'Siirretäänkö projekti roskakoriin? Työt ja raportit säilytetään ja ne voi palauttaa roskakorista.', '뜨개 차트': 'Neulekaavio', '사진 도안': 'Valokuvaohje', 'PDF 도안': 'PDF-ohje', '정보 저장': 'Tallenna tiedot', '보관 해제': 'Poista arkistosta', '변경을 되돌렸습니다.': 'Muutos kumottiin.', '저장 중': 'Tallennetaan', '사진 바꾸기': 'Vaihda kuva', '크게 보기': 'Näytä suurempana', '무늬단': 'Mallikerros', '메인 카운터 추가': 'Lisää päälaskuri', '추가 설정 접기': 'Piilota lisäasetukset', '추가 설정 펼치기': 'Näytä lisäasetukset', '고정 해제': 'Irrota kiinnitys', '상단 고정': 'Kiinnitä ylös', '수정': 'Muokkaa', '메인 카운터는 하나 이상 필요합니다': 'Päälaskureita tarvitaan vähintään yksi',
    '문구 미리보기': 'Tekstin esikatselu', '이미지를 열 수 없습니다.': 'Kuvaa ei voitu avata.', '합성할 사진을 선택해 주세요.': 'Valitse yhdistettävät kuvat.', '사진은 한 장에 최대 9개까지 담을 수 있습니다.': 'Yhdessä kuvassa voi olla enintään 9 valokuvaa.', '합성 이미지를 만들 수 없습니다.': 'Yhdistelmäkuvaa ei voitu luoda.', '사진이 너무 많아 한 장에 배치할 수 없습니다. 사진을 줄여 주세요.': 'Kuvia on liikaa yhteen kuvaan. Poista joitakin kuvia ja yritä uudelleen.', '합성 이미지를 저장하지 못했습니다.': 'Yhdistelmäkuvaa ei voitu tallentaa.', '이미지 만드는 중…': 'Luodaan kuvaa…', '이미지 만들기': 'Luo kuva', '뜨개 기록': 'Neulepäiväkirja', '한 코씩 완성해 가는 시간': 'Aikaa, jolloin työ valmistuu silmukka kerrallaan', '작업 과정': 'Työvaiheet', '뜨개 프로젝트': 'Neuleprojekti',
    '프로젝트 정보': 'Projektin tiedot', '도안 정보': 'Ohjeen tiedot', '사용한 실': 'Käytetty lanka', '바늘 · 부자재': 'Puikot ja tarvikkeet', '게이지 · 손땀': 'Neuletiheys ja käsiala', '사이즈 · 변형': 'Koko ja muutokset', '작업 과정 기록': 'Työvaiheen muistiinpanot', '완성 기록': 'Viimeistely', '뜨개 종류': 'Käsityötyyppi', '상태': 'Tila', 'CO (시작일)': 'Luo silmukat (aloituspäivä)', 'FO (완성일)': 'Päättele (valmistumispäivä)', '만든 대상': 'Kenelle tehty', '원작자 · 디자이너': 'Suunnittelija', '도안 출처': 'Ohjeen lähde', '도안 구매처': 'Ohje ostettu paikasta', '도안 링크': 'Ohjelinkki', '사용 언어': 'Ohjeen kieli', '원본 사이즈': 'Alkuperäiset koot', '선택 사이즈': 'Valittu koko', '디자인 특징': 'Mallin ominaisuudet', '도안 메모': 'Ohjemuistiinpanot', '브랜드': 'Tuotemerkki', '제품명': 'Tuote', '색상명': 'Väri', '색상번호': 'Värinumero', '성분': 'Kuitusisältö', '제조국': 'Valmistusmaa', '두께': 'Langan paksuus', '권장 바늘': 'Suositellut puikot', '한 타래 중량': 'Kerän paino', '한 타래 길이': 'Kerän pituus', '구매처': 'Ostopaikka', '구매 링크': 'Ostoslinkki', '구매 가격': 'Ostohinta', '구매 수량': 'Ostettu määrä', '사용 타래 수': 'Käytetyt kerät', '사용 중량': 'Käytetty paino', '사용 길이': 'Käytetty pituus', '남은 실': 'Ylijäänyt lanka', '구간': 'Osio', '바늘 종류': 'Puikkotyyppi', '사이즈': 'Koko', '케이블 길이': 'Kaapelin pituus', '종류': 'Tyyppi', '수량': 'Määrä', '상세': 'Lisätiedot', '측정 기준': 'Mittausperuste', '도안 게이지': 'Ohjeen neuletiheys', '세탁 전 게이지': 'Ennen pesua', '세탁 후 게이지': 'Pesun jälkeen', '많이 널손': 'Hyvin löysä', '널손': 'Löysä', '쫀손': 'Tiukka', '많이 쫀손': 'Hyvin tiukka', '원본(도안)': 'Alkuperäinen (ohje)', '변경 내용': 'Muutokset', '변형': 'Muunnelma', '작업 기록': 'Työmuistiinpano', '세탁 여부': 'Pesty', '세탁 방법': 'Pesutapa', '블로킹 방법': 'Pingotustapa', '세탁 전 크기': 'Mitat ennen pesua', '세탁 후 크기': 'Mitat pesun jälkeen', '세탁·블로킹 변화': 'Pesun ja pingotuksen muutokset', '난이도': 'Vaikeustaso', '전체 만족도': 'Kokonaistyytyväisyys', '실 만족도': 'Langan tyytyväisyys', '도안 만족도': 'Ohjeen tyytyväisyys', '다시 뜰 의향': 'Neuloisitko uudelleen', '문제와 해결': 'Ongelmat ja ratkaisut', '다음에 바꾸고 싶은 점': 'Mitä muuttaisit ensi kerralla', '완성 메모': 'Valmiin työn muistiinpanot', '기장': 'Pituus', '가슴둘레': 'Rinnanympärys', '소매길이': 'Hihan pituus', '항목': 'Kohta', '실': 'Lanka', '대표 사진': 'Kansikuva', '날짜 미설정': 'Päivämäärää ei asetettu', '설명 없음': 'Ei kuvausta',
    '분명 셌는데… 다시 셀게요.': 'Laskin sen varmasti… lasketaan uudelleen.', '도안보고, 뜨고, 또 도안보고.': 'Katso ohjetta, neulo, katso taas ohjetta.', '한 코씩 불러오는 중…': 'Ladataan silmukka kerrallaan…', '몇 단이었지… 다시 세는 중.': 'Monesko kerros olikaan? Lasketaan uudelleen…', '한 코가 어디 갔지?': 'Minne se silmukka katosi?', '푸를까… 그냥 갈까…': 'Puranko… vai jatkanko?', '실은 충분합니다. 아마도.': 'Lankaa pitäisi riittää. Ehkä.', '잠깐, 지금 겉뜨기였나?': 'Hetkinen, oliko se oikein?', '블로킹이 해결해 줄 거예요.': 'Pingotus kyllä auttaa.', '도안 해독 중…': 'Selvitetään ohjetta…',
    '대바늘': 'Neulonta', '코바늘': 'Virkkaus', '예정': 'Suunniteltu', '진행중': 'Kesken', '중단': 'Tauolla', '라글란': 'Raglan', '드롭숄더': 'Laskettu olkalinja', '브이넥': 'V-pääntie', '크롭': 'Lyhyt malli', '오버핏': 'Väljä istuvuus', '케이블': 'Palmikko', '배색': 'Värineule', '탑다운': 'Ylhäältä alas', '바텀업': 'Alhaalta ylös', '작게 느껴짐': 'Tuntuu pieneltä', '딱 맞음': 'Juuri sopiva', '여유 있음': 'Väljä', '많이 여유 있음': 'Hyvin väljä', '쉬움': 'Helppo', '어려움': 'Vaikea', '있음': 'Kyllä', '아니오': 'Ei', '실제': 'Todellinen',
  },
}

Object.assign(extendedTranslations.en, { '핏 · 완성 후기': 'Fit & finishing review', '기타 기록': 'Other notes', '실': 'Yarn', '바늘': 'Needles', '세탁 · 착용 후기': 'Washing and wear notes', '집중선': 'Focus band', '집중선 두께': 'Focus band height' })
Object.assign(extendedTranslations.ja, { '핏 · 완성 후기': '着用感・完成後の感想', '기타 기록': 'その他の記録', '실': '糸', '바늘': '針', '세탁 · 착용 후기': '洗濯・着用後の感想', '집중선': 'フォーカス帯', '집중선 두께': 'フォーカス帯の高さ' })
Object.assign(extendedTranslations.de, { '핏 · 완성 후기': 'Passform und Abschlussbewertung', '기타 기록': 'Weitere Notizen', '실': 'Garn', '바늘': 'Nadeln', '세탁 · 착용 후기': 'Wasch- und Trageerfahrungen', '집중선': 'Fokusbereich', '집중선 두께': 'Höhe des Fokusbereichs' })
Object.assign(extendedTranslations.da, { '핏 · 완성 후기': 'Pasform og afsluttende anmeldelse', '기타 기록': 'Andre noter', '실': 'Garn', '바늘': 'Pinde', '세탁 · 착용 후기': 'Vaske- og brugserfaringer', '집중선': 'Fokusområde', '집중선 두께': 'Fokusområdets højde' })
Object.assign(extendedTranslations.nb, { '핏 · 완성 후기': 'Passform og ferdig vurdering', '기타 기록': 'Andre notater', '실': 'Garn', '바늘': 'Pinner', '세탁 · 착용 후기': 'Vaske- og brukserfaringer', '집중선': 'Fokusområde', '집중선 두께': 'Fokusområdets høyde' })
Object.assign(extendedTranslations.fi, { '핏 · 완성 후기': 'Istuvuus ja viimeistelyarvio', '기타 기록': 'Muut muistiinpanot', '실': 'Lanka', '바늘': 'Puikot', '세탁 · 착용 후기': 'Pesu- ja käyttökokemukset', '집중선': 'Kohdistusalue', '집중선 두께': 'Kohdistusalueen korkeus' })
Object.assign(extendedTranslations.en, { '작업 타이머': 'Work timer', '재생': 'Play', '일시정지': 'Pause', '누적 작업시간': 'Total work time', '작업시간 메모': 'Work time note', '저장 재시도': 'Retry save', '일시정지를 눌러 시간을 저장하세요': 'Pause to save your time.', '작업시간을 저장하지 못했습니다. 같은 버튼을 눌러 재시도하세요.': 'Could not save work time. Press the same button to retry.', '저장되지 않은 작업시간': 'Unsaved work time', '마지막 저장 이후 측정한 시간은 저장되지 않습니다.': 'Time measured since the last save will be lost.', '나가기': 'Leave', '계속 작업': 'Keep working' })
Object.assign(extendedTranslations.ja, { '작업 타이머': '作業タイマー', '재생': '再生', '일시정지': '一時停止', '누적 작업시간': '累計作業時間', '작업시간 메모': '作業時間メモ', '저장 재시도': '保存を再試行', '일시정지를 눌러 시간을 저장하세요': '一時停止を押して時間を保存してください。', '작업시간을 저장하지 못했습니다. 같은 버튼을 눌러 재시도하세요.': '作業時間を保存できませんでした。同じボタンを押して再試行してください。', '저장되지 않은 작업시간': '未保存の作業時間', '마지막 저장 이후 측정한 시간은 저장되지 않습니다.': '前回保存後に計測した時間は保存されません。', '나가기': '終了', '계속 작업': '作業を続ける' })
Object.assign(extendedTranslations.de, { '작업 타이머': 'Arbeitszeit', '재생': 'Starten', '일시정지': 'Pausieren', '누적 작업시간': 'Gesamte Arbeitszeit', '작업시간 메모': 'Notiz zur Arbeitszeit', '저장 재시도': 'Speichern erneut versuchen', '일시정지를 눌러 시간을 저장하세요': 'Pausieren Sie, um die Zeit zu speichern.', '작업시간을 저장하지 못했습니다. 같은 버튼을 눌러 재시도하세요.': 'Arbeitszeit konnte nicht gespeichert werden. Drücken Sie dieselbe Taste erneut.', '저장되지 않은 작업시간': 'Nicht gespeicherte Arbeitszeit', '마지막 저장 이후 측정한 시간은 저장되지 않습니다.': 'Die seit dem letzten Speichern gemessene Zeit geht verloren.', '나가기': 'Verlassen', '계속 작업': 'Weiterarbeiten' })
Object.assign(extendedTranslations.da, { '작업 타이머': 'Arbejdstid', '재생': 'Start', '일시정지': 'Sæt på pause', '누적 작업시간': 'Samlet arbejdstid', '작업시간 메모': 'Note om arbejdstid', '저장 재시도': 'Prøv at gemme igen', '일시정지를 눌러 시간을 저장하세요': 'Sæt på pause for at gemme tiden.', '작업시간을 저장하지 못했습니다. 같은 버튼을 눌러 재시도하세요.': 'Arbejdstiden kunne ikke gemmes. Tryk på samme knap for at prøve igen.', '저장되지 않은 작업시간': 'Ikke-gemt arbejdstid', '마지막 저장 이후 측정한 시간은 저장되지 않습니다.': 'Tiden siden sidste lagring går tabt.', '나가기': 'Forlad', '계속 작업': 'Fortsæt arbejdet' })
Object.assign(extendedTranslations.nb, { '작업 타이머': 'Arbeidstid', '재생': 'Start', '일시정지': 'Sett på pause', '누적 작업시간': 'Samlet arbeidstid', '작업시간 메모': 'Notat om arbeidstid', '저장 재시도': 'Prøv å lagre på nytt', '일시정지를 눌러 시간을 저장하세요': 'Sett på pause for å lagre tiden.', '작업시간을 저장하지 못했습니다. 같은 버튼을 눌러 재시도하세요.': 'Kunne ikke lagre arbeidstiden. Trykk på samme knapp for å prøve igjen.', '저장되지 않은 작업시간': 'Ulagret arbeidstid', '마지막 저장 이후 측정한 시간은 저장되지 않습니다.': 'Tiden siden siste lagring går tapt.', '나가기': 'Forlat', '계속 작업': 'Fortsett arbeidet' })
Object.assign(extendedTranslations.fi, { '작업 타이머': 'Työajastin', '재생': 'Käynnistä', '일시정지': 'Keskeytä', '누적 작업시간': 'Työaika yhteensä', '작업시간 메모': 'Työaikamuistiinpano', '저장 재시도': 'Yritä tallentaa uudelleen', '일시정지를 눌러 시간을 저장하세요': 'Tallenna aika keskeyttämällä.', '작업시간을 저장하지 못했습니다. 같은 버튼을 눌러 재시도하세요.': 'Työajan tallennus epäonnistui. Yritä uudelleen samalla painikkeella.', '저장되지 않은 작업시간': 'Tallentamaton työaika', '마지막 저장 이후 측정한 시간은 저장되지 않습니다.': 'Viimeisimmän tallennuksen jälkeen mitattu aika katoaa.', '나가기': 'Poistu', '계속 작업': 'Jatka työskentelyä' })

const reportAndViewerErrors = {
  en: {
    '보고서를 불러오지 못했습니다.': 'Could not load the report.', '보고서를 추가하지 못했습니다.': 'Could not add the report.', '수정사항 후보를 분석하지 못했습니다.': 'Could not analyze suggested changes.', '선택한 수정사항을 저장하지 못했습니다.': 'Could not save the selected changes.', '후보를 제외하지 못했습니다.': 'Could not dismiss the suggestion.', 'PDF를 만들지 못했습니다.': 'Could not create the PDF.', '보고서를 저장하지 못했습니다.': 'Could not save the report.', '사진을 처리하지 못했습니다.': 'Could not process the photo.', '저장하지 못했습니다.': 'Could not save.', '저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Could not save. Check your available storage.', 'PDF 페이지 표시가 20초 안에 끝나지 않았습니다. 다시 시도해 주세요.': 'The PDF page did not finish rendering within 20 seconds. Please try again.', 'PDF 페이지를 표시하지 못했습니다.': 'Could not display the PDF page.', '차트 설정을 확인해 주세요.': 'Check the chart settings.', 'PDF 이름을 변경하지 못했습니다.': 'Could not rename the PDF.', '페이지를 숨기지 못했습니다.': 'Could not hide the page.', '숨김 그룹을 변경하지 못했습니다.': 'Could not change the hidden-page group.', '이름을 변경하지 못했습니다.': 'Could not rename.', '사진을 처리할 수 없습니다.': 'Could not process the photo.', '암호가 설정된 PDF입니다. 암호 없는 파일로 다시 시도해 주세요.': 'This PDF is password-protected. Try a file without a password.', 'PDF Worker를 시작하지 못했습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.': 'Could not start the PDF worker. Refresh the page and try again.', 'PDF를 읽지 못했습니다. 파일 접근 권한과 PDF 상태를 확인해 주세요.': 'Could not read the PDF. Check file access and the PDF file.'
  },
  ja: {
    '보고서를 불러오지 못했습니다.': 'レポートを読み込めませんでした。', '보고서를 추가하지 못했습니다.': 'レポートを追加できませんでした。', '수정사항 후보를 분석하지 못했습니다.': '変更候補を分析できませんでした。', '선택한 수정사항을 저장하지 못했습니다.': '選択した変更を保存できませんでした。', '후보를 제외하지 못했습니다.': '候補を除外できませんでした。', 'PDF를 만들지 못했습니다.': 'PDFを作成できませんでした。', '보고서를 저장하지 못했습니다.': 'レポートを保存できませんでした。', '사진을 처리하지 못했습니다.': '写真を処理できませんでした。', '저장하지 못했습니다.': '保存できませんでした。', '저장하지 못했습니다. 저장 공간을 확인해 주세요.': '保存できませんでした。空き容量を確認してください。', 'PDF 페이지 표시가 20초 안에 끝나지 않았습니다. 다시 시도해 주세요.': 'PDFページの表示が20秒以内に完了しませんでした。もう一度お試しください。', 'PDF 페이지를 표시하지 못했습니다.': 'PDFページを表示できませんでした。', '차트 설정을 확인해 주세요.': 'チャートの設定を確認してください。', 'PDF 이름을 변경하지 못했습니다.': 'PDFの名前を変更できませんでした。', '페이지를 숨기지 못했습니다.': 'ページを非表示にできませんでした。', '숨김 그룹을 변경하지 못했습니다.': '非表示ページのグループを変更できませんでした。', '이름을 변경하지 못했습니다.': '名前を変更できませんでした。', '사진을 처리할 수 없습니다.': '写真を処理できません。', '암호가 설정된 PDF입니다. 암호 없는 파일로 다시 시도해 주세요.': 'このPDFはパスワードで保護されています。パスワードのないファイルをお試しください。', 'PDF Worker를 시작하지 못했습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.': 'PDF Workerを起動できませんでした。ページを再読み込みして、もう一度お試しください。', 'PDF를 읽지 못했습니다. 파일 접근 권한과 PDF 상태를 확인해 주세요.': 'PDFを読み込めませんでした。ファイルへのアクセス権とPDFの状態を確認してください。'
  },
  de: {
    '보고서를 불러오지 못했습니다.': 'Der Bericht konnte nicht geladen werden.', '보고서를 추가하지 못했습니다.': 'Der Bericht konnte nicht hinzugefügt werden.', '수정사항 후보를 분석하지 못했습니다.': 'Änderungsvorschläge konnten nicht analysiert werden.', '선택한 수정사항을 저장하지 못했습니다.': 'Die ausgewählten Änderungen konnten nicht gespeichert werden.', '후보를 제외하지 못했습니다.': 'Der Vorschlag konnte nicht verworfen werden.', 'PDF를 만들지 못했습니다.': 'Das PDF konnte nicht erstellt werden.', '보고서를 저장하지 못했습니다.': 'Der Bericht konnte nicht gespeichert werden.', '사진을 처리하지 못했습니다.': 'Das Foto konnte nicht verarbeitet werden.', '저장하지 못했습니다.': 'Speichern fehlgeschlagen.', '저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Speichern fehlgeschlagen. Prüfen Sie den verfügbaren Speicherplatz.', 'PDF 페이지 표시가 20초 안에 끝나지 않았습니다. 다시 시도해 주세요.': 'Die PDF-Seite wurde nicht innerhalb von 20 Sekunden gerendert. Bitte versuchen Sie es erneut.', 'PDF 페이지를 표시하지 못했습니다.': 'Die PDF-Seite konnte nicht angezeigt werden.', '차트 설정을 확인해 주세요.': 'Bitte überprüfen Sie die Diagrammeinstellungen.', 'PDF 이름을 변경하지 못했습니다.': 'Das PDF konnte nicht umbenannt werden.', '페이지를 숨기지 못했습니다.': 'Die Seite konnte nicht ausgeblendet werden.', '숨김 그룹을 변경하지 못했습니다.': 'Die Gruppe ausgeblendeter Seiten konnte nicht geändert werden.', '이름을 변경하지 못했습니다.': 'Der Name konnte nicht geändert werden.', '사진을 처리할 수 없습니다.': 'Das Foto kann nicht verarbeitet werden.', '암호가 설정된 PDF입니다. 암호 없는 파일로 다시 시도해 주세요.': 'Dieses PDF ist passwortgeschützt. Bitte versuchen Sie es mit einer Datei ohne Passwort.', 'PDF Worker를 시작하지 못했습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.': 'Der PDF-Worker konnte nicht gestartet werden. Laden Sie die Seite neu und versuchen Sie es erneut.', 'PDF를 읽지 못했습니다. 파일 접근 권한과 PDF 상태를 확인해 주세요.': 'Das PDF konnte nicht gelesen werden. Prüfen Sie den Dateizugriff und die PDF-Datei.'
  },
  da: {
    '보고서를 불러오지 못했습니다.': 'Rapporten kunne ikke indlæses.', '보고서를 추가하지 못했습니다.': 'Rapporten kunne ikke tilføjes.', '수정사항 후보를 분석하지 못했습니다.': 'Forslag til ændringer kunne ikke analyseres.', '선택한 수정사항을 저장하지 못했습니다.': 'De valgte ændringer kunne ikke gemmes.', '후보를 제외하지 못했습니다.': 'Forslaget kunne ikke afvises.', 'PDF를 만들지 못했습니다.': 'PDF-filen kunne ikke oprettes.', '보고서를 저장하지 못했습니다.': 'Rapporten kunne ikke gemmes.', '사진을 처리하지 못했습니다.': 'Billedet kunne ikke behandles.', '저장하지 못했습니다.': 'Kunne ikke gemme.', '저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Kunne ikke gemme. Kontrollér den ledige lagerplads.', 'PDF 페이지 표시가 20초 안에 끝나지 않았습니다. 다시 시도해 주세요.': 'PDF-siden blev ikke vist inden for 20 sekunder. Prøv igen.', 'PDF 페이지를 표시하지 못했습니다.': 'PDF-siden kunne ikke vises.', '차트 설정을 확인해 주세요.': 'Kontrollér diagramindstillingerne.', 'PDF 이름을 변경하지 못했습니다.': 'PDF-filen kunne ikke omdøbes.', '페이지를 숨기지 못했습니다.': 'Siden kunne ikke skjules.', '숨김 그룹을 변경하지 못했습니다.': 'Gruppen af skjulte sider kunne ikke ændres.', '이름을 변경하지 못했습니다.': 'Navnet kunne ikke ændres.', '사진을 처리할 수 없습니다.': 'Billedet kan ikke behandles.', '암호가 설정된 PDF입니다. 암호 없는 파일로 다시 시도해 주세요.': 'Denne PDF er adgangskodebeskyttet. Prøv en fil uden adgangskode.', 'PDF Worker를 시작하지 못했습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.': 'PDF-arbejderen kunne ikke startes. Genindlæs siden, og prøv igen.', 'PDF를 읽지 못했습니다. 파일 접근 권한과 PDF 상태를 확인해 주세요.': 'PDF-filen kunne ikke læses. Kontrollér filadgang og PDF-filens tilstand.'
  },
  nb: {
    '보고서를 불러오지 못했습니다.': 'Kunne ikke laste inn rapporten.', '보고서를 추가하지 못했습니다.': 'Kunne ikke legge til rapporten.', '수정사항 후보를 분석하지 못했습니다.': 'Kunne ikke analysere foreslåtte endringer.', '선택한 수정사항을 저장하지 못했습니다.': 'Kunne ikke lagre de valgte endringene.', '후보를 제외하지 못했습니다.': 'Kunne ikke avvise forslaget.', 'PDF를 만들지 못했습니다.': 'Kunne ikke opprette PDF-filen.', '보고서를 저장하지 못했습니다.': 'Kunne ikke lagre rapporten.', '사진을 처리하지 못했습니다.': 'Kunne ikke behandle bildet.', '저장하지 못했습니다.': 'Kunne ikke lagre.', '저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Kunne ikke lagre. Kontroller tilgjengelig lagringsplass.', 'PDF 페이지 표시가 20초 안에 끝나지 않았습니다. 다시 시도해 주세요.': 'PDF-siden ble ikke vist innen 20 sekunder. Prøv på nytt.', 'PDF 페이지를 표시하지 못했습니다.': 'Kunne ikke vise PDF-siden.', '차트 설정을 확인해 주세요.': 'Kontroller diagraminnstillingene.', 'PDF 이름을 변경하지 못했습니다.': 'Kunne ikke gi PDF-filen nytt navn.', '페이지를 숨기지 못했습니다.': 'Kunne ikke skjule siden.', '숨김 그룹을 변경하지 못했습니다.': 'Kunne ikke endre gruppen med skjulte sider.', '이름을 변경하지 못했습니다.': 'Kunne ikke endre navnet.', '사진을 처리할 수 없습니다.': 'Kan ikke behandle bildet.', '암호가 설정된 PDF입니다. 암호 없는 파일로 다시 시도해 주세요.': 'Denne PDF-filen er passordbeskyttet. Prøv en fil uten passord.', 'PDF Worker를 시작하지 못했습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.': 'Kunne ikke starte PDF-arbeideren. Oppdater siden og prøv igjen.', 'PDF를 읽지 못했습니다. 파일 접근 권한과 PDF 상태를 확인해 주세요.': 'Kunne ikke lese PDF-filen. Kontroller filtilgang og PDF-filen.'
  },
  fi: {
    '보고서를 불러오지 못했습니다.': 'Raportin lataaminen epäonnistui.', '보고서를 추가하지 못했습니다.': 'Raportin lisääminen epäonnistui.', '수정사항 후보를 분석하지 못했습니다.': 'Ehdotettujen muutosten analysointi epäonnistui.', '선택한 수정사항을 저장하지 못했습니다.': 'Valittujen muutosten tallentaminen epäonnistui.', '후보를 제외하지 못했습니다.': 'Ehdotuksen hylkääminen epäonnistui.', 'PDF를 만들지 못했습니다.': 'PDF:n luominen epäonnistui.', '보고서를 저장하지 못했습니다.': 'Raportin tallentaminen epäonnistui.', '사진을 처리하지 못했습니다.': 'Kuvan käsittely epäonnistui.', '저장하지 못했습니다.': 'Tallennus epäonnistui.', '저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Tallennus epäonnistui. Tarkista käytettävissä oleva tallennustila.', 'PDF 페이지 표시가 20초 안에 끝나지 않았습니다. 다시 시도해 주세요.': 'PDF-sivun hahmontaminen ei valmistunut 20 sekunnissa. Yritä uudelleen.', 'PDF 페이지를 표시하지 못했습니다.': 'PDF-sivun näyttäminen epäonnistui.', '차트 설정을 확인해 주세요.': 'Tarkista kaavion asetukset.', 'PDF 이름을 변경하지 못했습니다.': 'PDF:n uudelleennimeäminen epäonnistui.', '페이지를 숨기지 못했습니다.': 'Sivun piilottaminen epäonnistui.', '숨김 그룹을 변경하지 못했습니다.': 'Piilotettujen sivujen ryhmän muuttaminen epäonnistui.', '이름을 변경하지 못했습니다.': 'Nimen muuttaminen epäonnistui.', '사진을 처리할 수 없습니다.': 'Kuvaa ei voi käsitellä.', '암호가 설정된 PDF입니다. 암호 없는 파일로 다시 시도해 주세요.': 'Tämä PDF on suojattu salasanalla. Kokeile tiedostoa, jossa ei ole salasanaa.', 'PDF Worker를 시작하지 못했습니다. 페이지를 새로고침한 뒤 다시 시도해 주세요.': 'PDF-työntekijän käynnistys epäonnistui. Lataa sivu uudelleen ja yritä uudestaan.', 'PDF를 읽지 못했습니다. 파일 접근 권한과 PDF 상태를 확인해 주세요.': 'PDF:n lukeminen epäonnistui. Tarkista tiedoston käyttöoikeudet ja PDF-tiedosto.'
  },
}
Object.assign(extendedTranslations.en, reportAndViewerErrors.en)
Object.assign(extendedTranslations.ja, reportAndViewerErrors.ja)
Object.assign(extendedTranslations.de, reportAndViewerErrors.de)
Object.assign(extendedTranslations.da, reportAndViewerErrors.da)
Object.assign(extendedTranslations.nb, reportAndViewerErrors.nb)
Object.assign(extendedTranslations.fi, reportAndViewerErrors.fi)
Object.assign(extendedTranslations.en, { '저장됨': 'Saved' })
Object.assign(extendedTranslations.ja, { '저장됨': '保存済み' })
Object.assign(extendedTranslations.de, { '저장됨': 'Gespeichert' })
Object.assign(extendedTranslations.da, { '저장됨': 'Gemt' })
Object.assign(extendedTranslations.nb, { '저장됨': 'Lagret' })
Object.assign(extendedTranslations.fi, { '저장됨': 'Tallennettu' })
const uiStatusTranslations = {
  en: { '불러오지 못했습니다. 페이지를 다시 열어 주세요.': 'Could not load it. Reopen the page.', '저장 중…': 'Saving…', '보고서 준비 중…': 'Preparing report…', '사진 처리 중…': 'Processing photos…', 'IG 문구가 복사됐어요.': 'Instagram caption copied.', '보고서가 변경되어 사진을 추가하지 못했습니다.': 'The report changed, so the photo could not be added.', '뷰어 위치를 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Could not save the viewer position. Check available storage and try again.', '페이지 작업을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Could not save page work. Check available storage and try again.', '일부 작업을 저장하지 못했습니다. 인터넷 연결을 확인하고 복귀 후 다시 저장해 주세요.': 'Some work could not be saved. Check your connection and save again when you return.', 'PDF 메모리를 해제하지 못했습니다. 다시 열어 주세요.': 'Could not release PDF memory. Reopen it.', '카운터와 진행선을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Could not save counters and progress lines. Check available storage and try again.', '기존 숨김 그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Could not save the existing hidden-page group. Check available storage.', '파일이 비어 있습니다.': 'The file is empty.', '브라우저 저장소에 기록하지 못했습니다.': 'Could not save to browser storage.', '{count}개 추가 완료. ': 'Added {count}. ', ' 외 {count}개 파일을 추가하지 못했습니다.': ' and {count} more file(s) could not be added.', '브라우저 저장 공간이 부족해 사진을 저장하지 못했습니다. 저장 공간을 확보한 뒤 다시 시도해 주세요.': 'There is not enough browser storage to save the photo. Free up space and try again.' },
  ja: { '불러오지 못했습니다. 페이지를 다시 열어 주세요.': '読み込めませんでした。ページを開き直してください。', '저장 중…': '保存中…', '보고서 준비 중…': 'レポートを準備中…', '사진 처리 중…': '写真を処理中…', 'IG 문구가 복사됐어요.': 'Instagramのキャプションをコピーしました。', '보고서가 변경되어 사진을 추가하지 못했습니다.': 'レポートが変更されたため、写真を追加できませんでした。', '뷰어 위치를 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'ビューアの位置を保存できませんでした。空き容量を確認して、もう一度お試しください。', '페이지 작업을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'ページの作業を保存できませんでした。空き容量を確認して、もう一度お試しください。', '일부 작업을 저장하지 못했습니다. 인터넷 연결을 확인하고 복귀 후 다시 저장해 주세요.': '一部の作業を保存できませんでした。接続を確認し、戻った後にもう一度保存してください。', 'PDF 메모리를 해제하지 못했습니다. 다시 열어 주세요.': 'PDFのメモリを解放できませんでした。開き直してください。', '카운터와 진행선을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'カウンターと進行線を保存できませんでした。空き容量を確認して、もう一度お試しください。', '기존 숨김 그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': '既存の非表示ページグループを保存できませんでした。空き容量を確認してください。', '파일이 비어 있습니다.': 'ファイルが空です。', '브라우저 저장소에 기록하지 못했습니다.': 'ブラウザーのストレージに保存できませんでした。', '{count}개 추가 완료. ': '{count}件を追加しました。', ' 외 {count}개 파일을 추가하지 못했습니다.': 'ほか{count}件のファイルを追加できませんでした。', '브라우저 저장 공간이 부족해 사진을 저장하지 못했습니다. 저장 공간을 확보한 뒤 다시 시도해 주세요.': 'ブラウザーの空き容量が不足しているため写真を保存できませんでした。空き容量を確保して、もう一度お試しください。' },
  de: { '불러오지 못했습니다. 페이지를 다시 열어 주세요.': 'Laden fehlgeschlagen. Öffnen Sie die Seite erneut.', '저장 중…': 'Wird gespeichert…', '보고서 준비 중…': 'Bericht wird vorbereitet…', '사진 처리 중…': 'Fotos werden verarbeitet…', 'IG 문구가 복사됐어요.': 'Instagram-Beschreibung kopiert.', '보고서가 변경되어 사진을 추가하지 못했습니다.': 'Der Bericht wurde geändert. Das Foto konnte nicht hinzugefügt werden.', '뷰어 위치를 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Die Viewer-Position konnte nicht gespeichert werden. Prüfen Sie den verfügbaren Speicherplatz und versuchen Sie es erneut.', '페이지 작업을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Die Seitenarbeit konnte nicht gespeichert werden. Prüfen Sie den verfügbaren Speicherplatz und versuchen Sie es erneut.', '일부 작업을 저장하지 못했습니다. 인터넷 연결을 확인하고 복귀 후 다시 저장해 주세요.': 'Ein Teil der Arbeit konnte nicht gespeichert werden. Prüfen Sie die Verbindung und speichern Sie sie nach Ihrer Rückkehr erneut.', 'PDF 메모리를 해제하지 못했습니다. 다시 열어 주세요.': 'Der PDF-Speicher konnte nicht freigegeben werden. Öffnen Sie die Datei erneut.', '카운터와 진행선을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Zähler und Fortschrittslinien konnten nicht gespeichert werden. Prüfen Sie den verfügbaren Speicherplatz und versuchen Sie es erneut.', '기존 숨김 그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Die bestehende Gruppe ausgeblendeter Seiten konnte nicht gespeichert werden. Prüfen Sie den verfügbaren Speicherplatz.', '파일이 비어 있습니다.': 'Die Datei ist leer.', '브라우저 저장소에 기록하지 못했습니다.': 'Speichern im Browserspeicher fehlgeschlagen.', '{count}개 추가 완료. ': '{count} hinzugefügt. ', ' 외 {count}개 파일을 추가하지 못했습니다.': ' und {count} weitere Datei(en) konnten nicht hinzugefügt werden.', '브라우저 저장 공간이 부족해 사진을 저장하지 못했습니다. 저장 공간을 확보한 뒤 다시 시도해 주세요.': 'Der Browser-Speicherplatz reicht zum Speichern des Fotos nicht aus. Geben Sie Speicherplatz frei und versuchen Sie es erneut.' },
  da: { '불러오지 못했습니다. 페이지를 다시 열어 주세요.': 'Kunne ikke indlæse. Åbn siden igen.', '저장 중…': 'Gemmer…', '보고서 준비 중…': 'Forbereder rapport…', '사진 처리 중…': 'Behandler fotos…', 'IG 문구가 복사됐어요.': 'Instagram-teksten er kopieret.', '보고서가 변경되어 사진을 추가하지 못했습니다.': 'Rapporten blev ændret, så billedet kunne ikke tilføjes.', '뷰어 위치를 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Kunne ikke gemme visningspositionen. Kontrollér den ledige lagerplads, og prøv igen.', '페이지 작업을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Kunne ikke gemme sidearbejdet. Kontrollér den ledige lagerplads, og prøv igen.', '일부 작업을 저장하지 못했습니다. 인터넷 연결을 확인하고 복귀 후 다시 저장해 주세요.': 'Noget arbejde kunne ikke gemmes. Kontrollér forbindelsen, og gem igen, når du vender tilbage.', 'PDF 메모리를 해제하지 못했습니다. 다시 열어 주세요.': 'Kunne ikke frigøre PDF-hukommelsen. Åbn igen.', '카운터와 진행선을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Kunne ikke gemme tællere og fremgangslinjer. Kontrollér lagerpladsen, og prøv igen.', '기존 숨김 그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Kunne ikke gemme den eksisterende gruppe af skjulte sider. Kontrollér lagerpladsen.', '파일이 비어 있습니다.': 'Filen er tom.', '브라우저 저장소에 기록하지 못했습니다.': 'Kunne ikke gemme i browserlageret.', '{count}개 추가 완료. ': '{count} tilføjet. ', ' 외 {count}개 파일을 추가하지 못했습니다.': ' og {count} yderligere fil(er) kunne ikke tilføjes.', '브라우저 저장 공간이 부족해 사진을 저장하지 못했습니다. 저장 공간을 확보한 뒤 다시 시도해 주세요.': 'Der er ikke nok browserlagerplads til at gemme billedet. Frigør plads, og prøv igen.' },
  nb: { '불러오지 못했습니다. 페이지를 다시 열어 주세요.': 'Kunne ikke laste inn. Åpne siden på nytt.', '저장 중…': 'Lagrer…', '보고서 준비 중…': 'Forbereder rapport…', '사진 처리 중…': 'Behandler bilder…', 'IG 문구가 복사됐어요.': 'Instagram-teksten er kopiert.', '보고서가 변경되어 사진을 추가하지 못했습니다.': 'Rapporten ble endret, så bildet kunne ikke legges til.', '뷰어 위치를 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Kunne ikke lagre visningsposisjonen. Kontroller tilgjengelig lagringsplass, og prøv igjen.', '페이지 작업을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Kunne ikke lagre sidearbeidet. Kontroller tilgjengelig lagringsplass, og prøv igjen.', '일부 작업을 저장하지 못했습니다. 인터넷 연결을 확인하고 복귀 후 다시 저장해 주세요.': 'Noe arbeid kunne ikke lagres. Kontroller tilkoblingen og lagre på nytt når du kommer tilbake.', 'PDF 메모리를 해제하지 못했습니다. 다시 열어 주세요.': 'Kunne ikke frigjøre PDF-minnet. Åpne på nytt.', '카운터와 진행선을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Kunne ikke lagre tellere og fremdriftslinjer. Kontroller lagringsplassen og prøv igjen.', '기존 숨김 그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Kunne ikke lagre den eksisterende gruppen med skjulte sider. Kontroller lagringsplassen.', '파일이 비어 있습니다.': 'Filen er tom.', '브라우저 저장소에 기록하지 못했습니다.': 'Kunne ikke lagre i nettleserens lagring.', '{count}개 추가 완료. ': '{count} lagt til. ', ' 외 {count}개 파일을 추가하지 못했습니다.': ' og {count} flere filer kunne ikke legges til.', '브라우저 저장 공간이 부족해 사진을 저장하지 못했습니다. 저장 공간을 확보한 뒤 다시 시도해 주세요.': 'Det er ikke nok lagringsplass i nettleseren til å lagre bildet. Frigjør plass, og prøv igjen.' },
  fi: { '불러오지 못했습니다. 페이지를 다시 열어 주세요.': 'Lataaminen epäonnistui. Avaa sivu uudelleen.', '저장 중…': 'Tallennetaan…', '보고서 준비 중…': 'Valmistellaan raporttia…', '사진 처리 중…': 'Käsitellään kuvia…', 'IG 문구가 복사됐어요.': 'Instagram-teksti kopioitiin.', '보고서가 변경되어 사진을 추가하지 못했습니다.': 'Raporttia muutettiin, joten kuvaa ei voitu lisätä.', '뷰어 위치를 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Näkymän sijainnin tallennus epäonnistui. Tarkista käytettävissä oleva tallennustila ja yritä uudelleen.', '페이지 작업을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Sivun työn tallennus epäonnistui. Tarkista käytettävissä oleva tallennustila ja yritä uudelleen.', '일부 작업을 저장하지 못했습니다. 인터넷 연결을 확인하고 복귀 후 다시 저장해 주세요.': 'Osan työstä tallennus epäonnistui. Tarkista yhteys ja tallenna uudelleen palattuasi.', 'PDF 메모리를 해제하지 못했습니다. 다시 열어 주세요.': 'PDF-muistin vapauttaminen epäonnistui. Avaa uudelleen.', '카운터와 진행선을 저장하지 못했습니다. 저장 공간을 확인하고 다시 시도해 주세요.': 'Laskureiden ja etenemisviivojen tallennus epäonnistui. Tarkista tallennustila ja yritä uudelleen.', '기존 숨김 그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Piilotettujen sivujen ryhmän tallennus epäonnistui. Tarkista tallennustila.', '파일이 비어 있습니다.': 'Tiedosto on tyhjä.', '브라우저 저장소에 기록하지 못했습니다.': 'Tallennus selaimen tallennustilaan epäonnistui.', '{count}개 추가 완료. ': '{count} lisätty. ', ' 외 {count}개 파일을 추가하지 못했습니다.': ' ja {count} muuta tiedostoa ei voitu lisätä.', '브라우저 저장 공간이 부족해 사진을 저장하지 못했습니다. 저장 공간을 확보한 뒤 다시 시도해 주세요.': 'Selaimen tallennustila ei riitä kuvan tallentamiseen. Vapauta tilaa ja yritä uudelleen.' },
}
Object.assign(extendedTranslations.en, uiStatusTranslations.en)
Object.assign(extendedTranslations.ja, uiStatusTranslations.ja)
Object.assign(extendedTranslations.de, uiStatusTranslations.de)
Object.assign(extendedTranslations.da, uiStatusTranslations.da)
Object.assign(extendedTranslations.nb, uiStatusTranslations.nb)
Object.assign(extendedTranslations.fi, uiStatusTranslations.fi)
const contentErrors = {
  en: { '사진을 저장할 수 없습니다.': 'Could not save the photo.', '사진을 읽지 못했습니다.': 'Could not read the photo.', 'PDF 페이지를 만들 수 없습니다.': 'Could not create the PDF page.', 'PDF 렌더 메모리를 확보하지 못했습니다. 다른 탭을 닫고 다시 시도해 주세요.': 'Could not allocate memory to render the PDF. Close other tabs and try again.', '이 브라우저에서 PDF 화면을 만들 수 없습니다.': 'This browser cannot create the PDF view.', 'PDF 화면을 표시할 수 없습니다.': 'Could not display the PDF view.', 'PDF 화면을 표시할 메모리를 확보하지 못했습니다.': 'Could not allocate memory to display the PDF.', 'QR 분석에 실패했습니다.': 'QR analysis failed.', 'QR 분석 캔버스를 만들 수 없습니다.': 'Could not create a canvas for QR analysis.', 'QR 분석 페이지 렌더가 20초 동안 끝나지 않았습니다.': 'QR analysis rendering did not finish within 20 seconds.', 'PDF 자료를 찾을 수 없습니다.': 'Could not find the PDF data.', '사진을 표시하지 못했습니다.': 'Could not display the photo.', '사진 폴더가 닫혔습니다.': 'The photo folder is closed.', '사진 페이지를 찾을 수 없습니다.': 'Could not find the photo page.', '주 진행선을 선택해 주세요.': 'Select the main progress line.', '이 PDF를 찾을 수 없습니다. 도안 목록에서 다시 열어 주세요.': 'Could not find this PDF. Reopen it from your patterns.', '페이지 변경을 처리 중입니다.': 'A page change is already being processed.', 'PDF 페이지 상태를 불러오지 못했습니다.': 'Could not load the PDF page state.', '선택한 페이지를 확인하지 못했습니다.': 'Could not verify the selected page.', '사진 폴더에는 원본 PDF가 없습니다.': 'Photo folders do not contain an original PDF.', '차트 이미지를 만들지 못했습니다.': 'Could not create the chart image.', '이미지 내보내기를 시작하지 못했습니다.': 'Could not start image export.', 'PNG 파일을 만들지 못했습니다.': 'Could not create the PNG file.', '차트 크기는 1~200cm, 게이지는 1~200 사이의 정수로 입력해 주세요.': 'Chart dimensions must be 1–200 cm, and gauge values must be whole numbers from 1 to 200.', '계산된 격자는 가로와 세로 각각 200칸 이하여야 합니다.': 'The calculated grid must have no more than 200 cells in either direction.' },
  ja: { '사진을 저장할 수 없습니다.': '写真を保存できませんでした。', '사진을 읽지 못했습니다.': '写真を読み込めませんでした。', 'PDF 페이지를 만들 수 없습니다.': 'PDFページを作成できませんでした。', 'PDF 렌더 메모리를 확보하지 못했습니다. 다른 탭을 닫고 다시 시도해 주세요.': 'PDFの表示に必要なメモリを確保できませんでした。他のタブを閉じて、もう一度お試しください。', '이 브라우저에서 PDF 화면을 만들 수 없습니다.': 'このブラウザーではPDF画面を作成できません。', 'PDF 화면을 표시할 수 없습니다.': 'PDF画面を表示できませんでした。', 'PDF 화면을 표시할 메모리를 확보하지 못했습니다.': 'PDF画面の表示に必要なメモリを確保できませんでした。', 'QR 분석에 실패했습니다.': 'QRコードの解析に失敗しました。', 'QR 분석 캔버스를 만들 수 없습니다.': 'QR解析用のキャンバスを作成できませんでした。', 'QR 분석 페이지 렌더가 20초 동안 끝나지 않았습니다.': 'QR解析ページの描画が20秒以内に完了しませんでした。', 'PDF 자료를 찾을 수 없습니다.': 'PDFデータが見つかりません。', '사진을 표시하지 못했습니다.': '写真を表示できませんでした。', '사진 폴더가 닫혔습니다.': '写真フォルダーは閉じられています。', '사진 페이지를 찾을 수 없습니다.': '写真ページが見つかりません。', '주 진행선을 선택해 주세요.': 'メインの進行線を選択してください。', '이 PDF를 찾을 수 없습니다. 도안 목록에서 다시 열어 주세요.': 'このPDFが見つかりません。編み図一覧から開き直してください。', '페이지 변경을 처리 중입니다.': 'ページ変更を処理中です。', 'PDF 페이지 상태를 불러오지 못했습니다.': 'PDFページの状態を読み込めませんでした。', '선택한 페이지를 확인하지 못했습니다.': '選択したページを確認できませんでした。', '사진 폴더에는 원본 PDF가 없습니다.': '写真フォルダーには元のPDFはありません。', '차트 이미지를 만들지 못했습니다.': 'チャート画像を作成できませんでした。', '이미지 내보내기를 시작하지 못했습니다.': '画像の書き出しを開始できませんでした。', 'PNG 파일을 만들지 못했습니다.': 'PNGファイルを作成できませんでした。', '차트 크기는 1~200cm, 게이지는 1~200 사이의 정수로 입력해 주세요.': 'チャートの寸法は1～200 cm、ゲージは1～200の整数で入力してください。', '계산된 격자는 가로와 세로 각각 200칸 이하여야 합니다.': '計算後のグリッドは縦横それぞれ200マス以下にしてください。' },
  de: { '사진을 저장할 수 없습니다.': 'Das Foto konnte nicht gespeichert werden.', '사진을 읽지 못했습니다.': 'Das Foto konnte nicht gelesen werden.', 'PDF 페이지를 만들 수 없습니다.': 'Die PDF-Seite konnte nicht erstellt werden.', 'PDF 렌더 메모리를 확보하지 못했습니다. 다른 탭을 닫고 다시 시도해 주세요.': 'Es konnte nicht genügend Speicher für die PDF-Darstellung bereitgestellt werden. Schließen Sie andere Tabs und versuchen Sie es erneut.', '이 브라우저에서 PDF 화면을 만들 수 없습니다.': 'Dieser Browser kann die PDF-Ansicht nicht erstellen.', 'PDF 화면을 표시할 수 없습니다.': 'Die PDF-Ansicht konnte nicht angezeigt werden.', 'PDF 화면을 표시할 메모리를 확보하지 못했습니다.': 'Es konnte nicht genügend Speicher für die PDF-Anzeige bereitgestellt werden.', 'QR 분석에 실패했습니다.': 'Die QR-Analyse ist fehlgeschlagen.', 'QR 분석 캔버스를 만들 수 없습니다.': 'Die Canvas für die QR-Analyse konnte nicht erstellt werden.', 'QR 분석 페이지 렌더가 20초 동안 끝나지 않았습니다.': 'Das Rendern der QR-Analyse dauerte länger als 20 Sekunden.', 'PDF 자료를 찾을 수 없습니다.': 'Die PDF-Daten wurden nicht gefunden.', '사진을 표시하지 못했습니다.': 'Das Foto konnte nicht angezeigt werden.', '사진 폴더가 닫혔습니다.': 'Der Fotoordner ist geschlossen.', '사진 페이지를 찾을 수 없습니다.': 'Die Fotoseite wurde nicht gefunden.', '주 진행선을 선택해 주세요.': 'Wählen Sie die Hauptfortschrittslinie aus.', '이 PDF를 찾을 수 없습니다. 도안 목록에서 다시 열어 주세요.': 'Dieses PDF wurde nicht gefunden. Öffnen Sie es erneut in der Musterliste.', '페이지 변경을 처리 중입니다.': 'Ein Seitenwechsel wird bereits verarbeitet.', 'PDF 페이지 상태를 불러오지 못했습니다.': 'Der Status der PDF-Seite konnte nicht geladen werden.', '선택한 페이지를 확인하지 못했습니다.': 'Die ausgewählte Seite konnte nicht überprüft werden.', '사진 폴더에는 원본 PDF가 없습니다.': 'Fotoordner enthalten keine Original-PDF-Datei.', '차트 이미지를 만들지 못했습니다.': 'Das Diagrammbild konnte nicht erstellt werden.', '이미지 내보내기를 시작하지 못했습니다.': 'Der Bildexport konnte nicht gestartet werden.', 'PNG 파일을 만들지 못했습니다.': 'Die PNG-Datei konnte nicht erstellt werden.', '차트 크기는 1~200cm, 게이지는 1~200 사이의 정수로 입력해 주세요.': 'Die Diagrammgröße muss 1–200 cm betragen; die Maschenprobe muss eine ganze Zahl von 1 bis 200 sein.', '계산된 격자는 가로와 세로 각각 200칸 이하여야 합니다.': 'Das berechnete Raster darf in jeder Richtung höchstens 200 Zellen haben.' },
  da: { '사진을 저장할 수 없습니다.': 'Billedet kunne ikke gemmes.', '사진을 읽지 못했습니다.': 'Billedet kunne ikke læses.', 'PDF 페이지를 만들 수 없습니다.': 'PDF-siden kunne ikke oprettes.', 'PDF 렌더 메모리를 확보하지 못했습니다. 다른 탭을 닫고 다시 시도해 주세요.': 'Kunne ikke frigøre nok hukommelse til at vise PDF-filen. Luk andre faner, og prøv igen.', '이 브라우저에서 PDF 화면을 만들 수 없습니다.': 'Denne browser kan ikke oprette PDF-visningen.', 'PDF 화면을 표시할 수 없습니다.': 'PDF-visningen kunne ikke vises.', 'PDF 화면을 표시할 메모리를 확보하지 못했습니다.': 'Kunne ikke frigøre nok hukommelse til at vise PDF-filen.', 'QR 분석에 실패했습니다.': 'QR-analysen mislykkedes.', 'QR 분석 캔버스를 만들 수 없습니다.': 'Kunne ikke oprette et lærred til QR-analyse.', 'QR 분석 페이지 렌더가 20초 동안 끝나지 않았습니다.': 'QR-analyseringen blev ikke færdig inden for 20 sekunder.', 'PDF 자료를 찾을 수 없습니다.': 'PDF-dataene blev ikke fundet.', '사진을 표시하지 못했습니다.': 'Billedet kunne ikke vises.', '사진 폴더가 닫혔습니다.': 'Billedmappen er lukket.', '사진 페이지를 찾을 수 없습니다.': 'Billedsiden blev ikke fundet.', '주 진행선을 선택해 주세요.': 'Vælg hovedfremgangslinjen.', '이 PDF를 찾을 수 없습니다. 도안 목록에서 다시 열어 주세요.': 'PDF-filen blev ikke fundet. Åbn den igen fra dine mønstre.', '페이지 변경을 처리 중입니다.': 'Et sideskift behandles allerede.', 'PDF 페이지 상태를 불러오지 못했습니다.': 'PDF-sidens status kunne ikke indlæses.', '선택한 페이지를 확인하지 못했습니다.': 'Den valgte side kunne ikke bekræftes.', '사진 폴더에는 원본 PDF가 없습니다.': 'Billedmapper indeholder ikke en original PDF.', '차트 이미지를 만들지 못했습니다.': 'Diagrammet kunne ikke oprettes som billede.', '이미지 내보내기를 시작하지 못했습니다.': 'Kunne ikke starte eksport af billedet.', 'PNG 파일을 만들지 못했습니다.': 'PNG-filen kunne ikke oprettes.', '차트 크기는 1~200cm, 게이지는 1~200 사이의 정수로 입력해 주세요.': 'Diagrammets mål skal være 1–200 cm, og strikkefastheden skal være et helt tal fra 1 til 200.', '계산된 격자는 가로와 세로 각각 200칸 이하여야 합니다.': 'Det beregnede gitter må højst have 200 felter i hver retning.' },
  nb: { '사진을 저장할 수 없습니다.': 'Kunne ikke lagre bildet.', '사진을 읽지 못했습니다.': 'Kunne ikke lese bildet.', 'PDF 페이지를 만들 수 없습니다.': 'Kunne ikke opprette PDF-siden.', 'PDF 렌더 메모리를 확보하지 못했습니다. 다른 탭을 닫고 다시 시도해 주세요.': 'Kunne ikke frigjøre nok minne til å vise PDF-en. Lukk andre faner og prøv igjen.', '이 브라우저에서 PDF 화면을 만들 수 없습니다.': 'Denne nettleseren kan ikke opprette PDF-visningen.', 'PDF 화면을 표시할 수 없습니다.': 'Kunne ikke vise PDF-visningen.', 'PDF 화면을 표시할 메모리를 확보하지 못했습니다.': 'Kunne ikke frigjøre minne til å vise PDF-en.', 'QR 분석에 실패했습니다.': 'QR-analysen mislyktes.', 'QR 분석 캔버스를 만들 수 없습니다.': 'Kunne ikke opprette et lerret for QR-analyse.', 'QR 분석 페이지 렌더가 20초 동안 끝나지 않았습니다.': 'QR-analyseringen ble ikke ferdig innen 20 sekunder.', 'PDF 자료를 찾을 수 없습니다.': 'Fant ikke PDF-dataene.', '사진을 표시하지 못했습니다.': 'Kunne ikke vise bildet.', '사진 폴더가 닫혔습니다.': 'Bildefolderen er lukket.', '사진 페이지를 찾을 수 없습니다.': 'Fant ikke bildesiden.', '주 진행선을 선택해 주세요.': 'Velg hovedfremdriftslinjen.', '이 PDF를 찾을 수 없습니다. 도안 목록에서 다시 열어 주세요.': 'Fant ikke denne PDF-en. Åpne den på nytt fra mønsterlisten.', '페이지 변경을 처리 중입니다.': 'Et sideskifte behandles allerede.', 'PDF 페이지 상태를 불러오지 못했습니다.': 'Kunne ikke laste inn PDF-sidestatusen.', '선택한 페이지를 확인하지 못했습니다.': 'Kunne ikke bekrefte den valgte siden.', '사진 폴더에는 원본 PDF가 없습니다.': 'Bildefolderen inneholder ingen original PDF.', '차트 이미지를 만들지 못했습니다.': 'Kunne ikke opprette diagrammet som bilde.', '이미지 내보내기를 시작하지 못했습니다.': 'Kunne ikke starte bildeeksporten.', 'PNG 파일을 만들지 못했습니다.': 'Kunne ikke opprette PNG-filen.', '차트 크기는 1~200cm, 게이지는 1~200 사이의 정수로 입력해 주세요.': 'Diagrammets mål må være 1–200 cm, og strikkefastheten må være et helt tall fra 1 til 200.', '계산된 격자는 가로와 세로 각각 200칸 이하여야 합니다.': 'Det beregnede rutenettet kan ha maksimalt 200 ruter i hver retning.' },
  fi: { '사진을 저장할 수 없습니다.': 'Kuvan tallennus epäonnistui.', '사진을 읽지 못했습니다.': 'Kuvan lukeminen epäonnistui.', 'PDF 페이지를 만들 수 없습니다.': 'PDF-sivun luominen epäonnistui.', 'PDF 렌더 메모리를 확보하지 못했습니다. 다른 탭을 닫고 다시 시도해 주세요.': 'PDF:n näyttämiseen ei saatu riittävästi muistia. Sulje muut välilehdet ja yritä uudelleen.', '이 브라우저에서 PDF 화면을 만들 수 없습니다.': 'Tämä selain ei voi luoda PDF-näkymää.', 'PDF 화면을 표시할 수 없습니다.': 'PDF-näkymän näyttäminen epäonnistui.', 'PDF 화면을 표시할 메모리를 확보하지 못했습니다.': 'PDF:n näyttämiseen ei saatu riittävästi muistia.', 'QR 분석에 실패했습니다.': 'QR-koodin analysointi epäonnistui.', 'QR 분석 캔버스를 만들 수 없습니다.': 'QR-analyysin piirtoalustan luominen epäonnistui.', 'QR 분석 페이지 렌더가 20초 동안 끝나지 않았습니다.': 'QR-analyysisivun hahmontaminen kesti yli 20 sekuntia.', 'PDF 자료를 찾을 수 없습니다.': 'PDF-tietoja ei löytynyt.', '사진을 표시하지 못했습니다.': 'Kuvan näyttäminen epäonnistui.', '사진 폴더가 닫혔습니다.': 'Kuvakansio on suljettu.', '사진 페이지를 찾을 수 없습니다.': 'Kuva-sivua ei löytynyt.', '주 진행선을 선택해 주세요.': 'Valitse pääetenemisviiva.', '이 PDF를 찾을 수 없습니다. 도안 목록에서 다시 열어 주세요.': 'PDF-tiedostoa ei löytynyt. Avaa se uudelleen malliluettelosta.', '페이지 변경을 처리 중입니다.': 'Sivunvaihto on jo käsittelyssä.', 'PDF 페이지 상태를 불러오지 못했습니다.': 'PDF-sivun tilan lataaminen epäonnistui.', '선택한 페이지를 확인하지 못했습니다.': 'Valitun sivun vahvistaminen epäonnistui.', '사진 폴더에는 원본 PDF가 없습니다.': 'Kuvakansioissa ei ole alkuperäistä PDF-tiedostoa.', '차트 이미지를 만들지 못했습니다.': 'Kaavion kuvan luominen epäonnistui.', '이미지 내보내기를 시작하지 못했습니다.': 'Kuvan vientiä ei voitu aloittaa.', 'PNG 파일을 만들지 못했습니다.': 'PNG-tiedoston luominen epäonnistui.', '차트 크기는 1~200cm, 게이지는 1~200 사이의 정수로 입력해 주세요.': 'Kaavion mittojen on oltava 1–200 cm ja tiheyden kokonaisluku 1–200.', '계산된 격자는 가로와 세로 각각 200칸 이하여야 합니다.': 'Lasketussa ruudukossa saa olla enintään 200 solua kumpaankin suuntaan.' },
}
Object.assign(extendedTranslations.en, contentErrors.en)
Object.assign(extendedTranslations.ja, contentErrors.ja)
Object.assign(extendedTranslations.de, contentErrors.de)
Object.assign(extendedTranslations.da, contentErrors.da)
Object.assign(extendedTranslations.nb, contentErrors.nb)
Object.assign(extendedTranslations.fi, contentErrors.fi)
const uiNamingTranslations = {
  en: { '제목 없음': 'Untitled', '레이어 {count}': 'Layer {count}', '색상 {count}': 'Color {count}', '실 색상 {count}': 'Yarn color {count}', '{count}개 선택': '{count} selected', '표시': 'Show', '진행 {count}': 'Progress {count}' },
  ja: { '제목 없음': '無題', '레이어 {count}': 'レイヤー {count}', '색상 {count}': '色 {count}', '실 색상 {count}': '糸の色 {count}', '{count}개 선택': '{count}件選択中', '표시': '表示', '진행 {count}': '作業 {count}' },
  de: { '제목 없음': 'Ohne Titel', '레이어 {count}': 'Ebene {count}', '색상 {count}': 'Farbe {count}', '실 색상 {count}': 'Garnfarbe {count}', '{count}개 선택': '{count} ausgewählt', '표시': 'Anzeigen', '진행 {count}': 'Fortschritt {count}' },
  da: { '제목 없음': 'Uden titel', '레이어 {count}': 'Lag {count}', '색상 {count}': 'Farve {count}', '실 색상 {count}': 'Garnfarve {count}', '{count}개 선택': '{count} valgt', '표시': 'Vis', '진행 {count}': 'Fremskridt {count}' },
  nb: { '제목 없음': 'Uten tittel', '레이어 {count}': 'Lag {count}', '색상 {count}': 'Farge {count}', '실 색상 {count}': 'Garnfarge {count}', '{count}개 선택': '{count} valgt', '표시': 'Vis', '진행 {count}': 'Fremdrift {count}' },
  fi: { '제목 없음': 'Nimetön', '레이어 {count}': 'Taso {count}', '색상 {count}': 'Väri {count}', '실 색상 {count}': 'Langan väri {count}', '{count}개 선택': '{count} valittu', '표시': 'Näytä', '진행 {count}': 'Eteneminen {count}' },
}
Object.assign(extendedTranslations.en, uiNamingTranslations.en)
Object.assign(extendedTranslations.ja, uiNamingTranslations.ja)
Object.assign(extendedTranslations.de, uiNamingTranslations.de)
Object.assign(extendedTranslations.da, uiNamingTranslations.da)
Object.assign(extendedTranslations.nb, uiNamingTranslations.nb)
Object.assign(extendedTranslations.fi, uiNamingTranslations.fi)
Object.assign(extendedTranslations.en, { inch: 'inch' })
Object.assign(extendedTranslations.ja, { inch: 'インチ' })
Object.assign(extendedTranslations.de, { inch: 'Zoll' })
Object.assign(extendedTranslations.da, { inch: 'tommer' })
Object.assign(extendedTranslations.nb, { inch: 'tommer' })
Object.assign(extendedTranslations.fi, { inch: 'tuuma' })
const colorAndSymbolNames = {
  en: { '먹색': 'Ink black', '따뜻한 빨강': 'Warm red', '차분한 파랑': 'Muted blue', '차분한 초록': 'Muted green', '부드러운 보라': 'Soft purple', '회색': 'Gray', '진행선 코랄': 'Progress coral', '현재 색상': 'Current color', '사슬뜨기': 'Chain stitch', '빼뜨기': 'Slip stitch', '짧은뜨기': 'Single crochet', '긴뜨기': 'Half double crochet', '한길긴뜨기': 'Double crochet', '두길긴뜨기': 'Treble crochet' },
  ja: { '먹색': '墨色', '따뜻한 빨강': 'あたたかい赤', '차분한 파랑': '落ち着いた青', '차분한 초록': '落ち着いた緑', '부드러운 보라': 'やわらかな紫', '회색': 'グレー', '진행선 코랄': '進行線コーラル', '현재 색상': '現在の色', '사슬뜨기': '鎖編み', '빼뜨기': '引き抜き編み', '짧은뜨기': '細編み', '긴뜨기': '中長編み', '한길긴뜨기': '長編み', '두길긴뜨기': '長々編み' },
  de: { '먹색': 'Tintenschwarz', '따뜻한 빨강': 'Warmes Rot', '차분한 파랑': 'Gedämpftes Blau', '차분한 초록': 'Gedämpftes Grün', '부드러운 보라': 'Sanftes Violett', '회색': 'Grau', '진행선 코랄': 'Fortschrittslinie Koralle', '현재 색상': 'Aktuelle Farbe', '사슬뜨기': 'Luftmasche', '빼뜨기': 'Kettmasche', '짧은뜨기': 'Feste Masche', '긴뜨기': 'Halbes Stäbchen', '한길긴뜨기': 'Stäbchen', '두길긴뜨기': 'Doppelstäbchen' },
  da: { '먹색': 'Blæksort', '따뜻한 빨강': 'Varm rød', '차분한 파랑': 'Dæmpet blå', '차분한 초록': 'Dæmpet grøn', '부드러운 보라': 'Blød lilla', '회색': 'Grå', '진행선 코랄': 'Fremgangslinje koral', '현재 색상': 'Aktuel farve', '사슬뜨기': 'Luftmaske', '빼뜨기': 'Kædemaske', '짧은뜨기': 'Fastmaske', '긴뜨기': 'Halvstangmaske', '한길긴뜨기': 'Stangmaske', '두길긴뜨기': 'Dobbeltstangmaske' },
  nb: { '먹색': 'Blekkgrå', '따뜻한 빨강': 'Varm rød', '차분한 파랑': 'Dempet blå', '차분한 초록': 'Dempet grønn', '부드러운 보라': 'Myk lilla', '회색': 'Grå', '진행선 코랄': 'Fremdriftslinje korall', '현재 색상': 'Gjeldende farge', '사슬뜨기': 'Luftmaske', '빼뜨기': 'Kjedemaske', '짧은뜨기': 'Fastmaske', '긴뜨기': 'Halvstav', '한길긴뜨기': 'Stav', '두길긴뜨기': 'Dobbeltstav' },
  fi: { '먹색': 'Musteenväri', '따뜻한 빨강': 'Lämmin punainen', '차분한 파랑': 'Hillitty sininen', '차분한 초록': 'Hillitty vihreä', '부드러운 보라': 'Pehmeä violetti', '회색': 'Harmaa', '진행선 코랄': 'Etenemisviiva koralli', '현재 색상': 'Nykyinen väri', '사슬뜨기': 'Ketjusilmukka', '빼뜨기': 'Piilosilmukka', '짧은뜨기': 'Kiinteä silmukka', '긴뜨기': 'Puolipylväs', '한길긴뜨기': 'Pylväs', '두길긴뜨기': 'Pitkä pylväs' },
}
Object.assign(extendedTranslations.en, colorAndSymbolNames.en)
Object.assign(extendedTranslations.ja, colorAndSymbolNames.ja)
Object.assign(extendedTranslations.de, colorAndSymbolNames.de)
Object.assign(extendedTranslations.da, colorAndSymbolNames.da)
Object.assign(extendedTranslations.nb, colorAndSymbolNames.nb)
Object.assign(extendedTranslations.fi, colorAndSymbolNames.fi)
const utilityLabels = {
  en: { '실제': 'Actual', '뷰어 도구': 'Viewer tools', '도구 설정': 'Tool settings', '작업 타이머 이동': 'Move work timer' },
  ja: { '실제': '実際', '뷰어 도구': 'ビューアツール', '도구 설정': 'ツール設定', '작업 타이머 이동': '作業タイマーを移動' },
  de: { '실제': 'Tatsächlich', '뷰어 도구': 'Viewer-Werkzeuge', '도구 설정': 'Werkzeugeinstellungen', '작업 타이머 이동': 'Arbeitstimer verschieben' },
  da: { '실제': 'Faktisk', '뷰어 도구': 'Visningsværktøjer', '도구 설정': 'Værktøjsindstillinger', '작업 타이머 이동': 'Flyt arbejdstimer' },
  nb: { '실제': 'Faktisk', '뷰어 도구': 'Visningsverktøy', '도구 설정': 'Verktøyinnstillinger', '작업 타이머 이동': 'Flytt arbeidstimer' },
  fi: { '실제': 'Todellinen', '뷰어 도구': 'Katselutyökalut', '도구 설정': 'Työkalun asetukset', '작업 타이머 이동': 'Siirrä työajastinta' },
}
Object.assign(extendedTranslations.en, utilityLabels.en)
Object.assign(extendedTranslations.ja, utilityLabels.ja)
Object.assign(extendedTranslations.de, utilityLabels.de)
Object.assign(extendedTranslations.da, utilityLabels.da)
Object.assign(extendedTranslations.nb, utilityLabels.nb)
Object.assign(extendedTranslations.fi, utilityLabels.fi)
const dynamicAccessibility = {
  en: { '{page}페이지 숨김, 클릭하여 숨김 해제': 'Page {page} is hidden. Click to restore it.', '{page}페이지 썸네일': 'Page {page} thumbnail', 'PDF {page}페이지': 'PDF page {page}', '웹 링크 새 탭 열기 {count}': 'Open web link {count} in a new tab', 'QR 링크 열기 {count}': 'Open QR link {count}', '{columns}코 {rows}단 컬러워크 모눈. 클릭하거나 드래그하여 칠합니다.': 'Colorwork grid, {columns} stitches by {rows} rows. Click or drag to color cells.', '{name} 메뉴': '{name} menu', '{name} 상세': '{name} details', '선택한 {count}개 페이지 숨김': 'Hide {count} selected pages', '{pages}페이지 {action}': 'Pages {pages}: {action}', '{count}개 페이지 {action}': '{action} {count} pages', '{page}페이지 숨기기': 'Hide page {page}', '90도 회전 · 현재 {angle}도': 'Rotate 90° · currently {angle}°', '확대 배율 {zoom}%': 'Zoom {zoom}%', '현재 {row}단': 'Current row {row}', '{name} 감소': 'Decrease {name}', '{name} 증가': 'Increase {name}' },
  ja: { '{page}페이지 숨김, 클릭하여 숨김 해제': 'ページ{page}は非表示です。クリックして表示します。', '{page}페이지 썸네일': 'ページ{page}のサムネイル', 'PDF {page}페이지': 'PDFの{page}ページ', '웹 링크 새 탭 열기 {count}': 'ウェブリンク{count}を新しいタブで開く', 'QR 링크 열기 {count}': 'QRリンク{count}を開く', '{columns}코 {rows}단 컬러워크 모눈. 클릭하거나 드래그하여 칠합니다.': 'カラー編みグリッド。{columns}目×{rows}段。クリックまたはドラッグして色を塗ります。', '{name} 메뉴': '{name}メニュー', '{name} 상세': '{name}の詳細', '선택한 {count}개 페이지 숨김': '選択した{count}ページを非表示', '{pages}페이지 {action}': 'ページ{pages}：{action}', '{count}개 페이지 {action}': '{count}ページを{action}', '{page}페이지 숨기기': 'ページ{page}を非表示', '90도 회전 · 현재 {angle}도': '90°回転・現在{angle}°', '확대 배율 {zoom}%': 'ズーム{zoom}%', '현재 {row}단': '現在{row}段', '{name} 감소': '{name}を減らす', '{name} 증가': '{name}を増やす' },
  de: { '{page}페이지 숨김, 클릭하여 숨김 해제': 'Seite {page} ist ausgeblendet. Zum Wiederherstellen anklicken.', '{page}페이지 썸네일': 'Miniaturansicht von Seite {page}', 'PDF {page}페이지': 'PDF-Seite {page}', '웹 링크 새 탭 열기 {count}': 'Weblink {count} in neuem Tab öffnen', 'QR 링크 열기 {count}': 'QR-Link {count} öffnen', '{columns}코 {rows}단 컬러워크 모눈. 클릭하거나 드래그하여 칠합니다.': 'Farbmuster-Raster mit {columns} Maschen und {rows} Reihen. Zum Ausmalen klicken oder ziehen.', '{name} 메뉴': 'Menü für {name}', '{name} 상세': 'Details zu {name}', '선택한 {count}개 페이지 숨김': '{count} ausgewählte Seiten ausblenden', '{pages}페이지 {action}': 'Seiten {pages}: {action}', '{count}개 페이지 {action}': '{action} {count} Seiten', '{page}페이지 숨기기': 'Seite {page} ausblenden', '90도 회전 · 현재 {angle}도': '90° drehen · aktuell {angle}°', '확대 배율 {zoom}%': 'Zoom {zoom} %', '현재 {row}단': 'Aktuelle Reihe {row}', '{name} 감소': '{name} verringern', '{name} 증가': '{name} erhöhen' },
  da: { '{page}페이지 숨김, 클릭하여 숨김 해제': 'Side {page} er skjult. Klik for at gendanne den.', '{page}페이지 썸네일': 'Miniature af side {page}', 'PDF {page}페이지': 'PDF-side {page}', '웹 링크 새 탭 열기 {count}': 'Åbn weblink {count} i en ny fane', 'QR 링크 열기 {count}': 'Åbn QR-link {count}', '{columns}코 {rows}단 컬러워크 모눈. 클릭하거나 드래그하여 칠합니다.': 'Farvestriksgitter med {columns} masker og {rows} pinde. Klik eller træk for at farvelægge felter.', '{name} 메뉴': 'Menu for {name}', '{name} 상세': 'Detaljer om {name}', '선택한 {count}개 페이지 숨김': 'Skjul {count} valgte sider', '{pages}페이지 {action}': 'Sider {pages}: {action}', '{count}개 페이지 {action}': '{action} {count} sider', '{page}페이지 숨기기': 'Skjul side {page}', '90도 회전 · 현재 {angle}도': 'Rotér 90° · aktuelt {angle}°', '확대 배율 {zoom}%': 'Zoom {zoom} %', '현재 {row}단': 'Aktuel pind {row}', '{name} 감소': 'Sænk {name}', '{name} 증가': 'Øg {name}' },
  nb: { '{page}페이지 숨김, 클릭하여 숨김 해제': 'Side {page} er skjult. Klikk for å gjenopprette den.', '{page}페이지 썸네일': 'Miniatyrbilde av side {page}', 'PDF {page}페이지': 'PDF-side {page}', '웹 링크 새 탭 열기 {count}': 'Åpne nettlenke {count} i en ny fane', 'QR 링크 열기 {count}': 'Åpne QR-lenke {count}', '{columns}코 {rows}단 컬러워크 모눈. 클릭하거나 드래그하여 칠합니다.': 'Fargestrikkrutenett med {columns} masker og {rows} rader. Klikk eller dra for å fargelegge ruter.', '{name} 메뉴': 'Meny for {name}', '{name} 상세': 'Detaljer om {name}', '선택한 {count}개 페이지 숨김': 'Skjul {count} valgte sider', '{pages}페이지 {action}': 'Sider {pages}: {action}', '{count}개 페이지 {action}': '{action} {count} sider', '{page}페이지 숨기기': 'Skjul side {page}', '90도 회전 · 현재 {angle}도': 'Roter 90° · nå {angle}°', '확대 배율 {zoom}%': 'Zoom {zoom} %', '현재 {row}단': 'Gjeldende rad {row}', '{name} 감소': 'Reduser {name}', '{name} 증가': 'Øk {name}' },
  fi: { '{page}페이지 숨김, 클릭하여 숨김 해제': 'Sivu {page} on piilotettu. Palauta se napsauttamalla.', '{page}페이지 썸네일': 'Sivun {page} pikkukuva', 'PDF {page}페이지': 'PDF-sivu {page}', '웹 링크 새 탭 열기 {count}': 'Avaa verkkolinkki {count} uudessa välilehdessä', 'QR 링크 열기 {count}': 'Avaa QR-linkki {count}', '{columns}코 {rows}단 컬러워크 모눈. 클릭하거나 드래그하여 칠합니다.': 'Värineuleverkko, {columns} silmukkaa ja {rows} kerrosta. Väritä napsauttamalla tai vetämällä.', '{name} 메뉴': '{name}-valikko', '{name} 상세': '{name} – tiedot', '선택한 {count}개 페이지 숨김': 'Piilota {count} valittua sivua', '{pages}페이지 {action}': 'Sivut {pages}: {action}', '{count}개 페이지 {action}': '{action} {count} sivua', '{page}페이지 숨기기': 'Piilota sivu {page}', '90도 회전 · 현재 {angle}도': 'Kierrä 90° · nyt {angle}°', '확대 배율 {zoom}%': 'Zoomaus {zoom} %', '현재 {row}단': 'Nykyinen kerros {row}', '{name} 감소': 'Vähennä: {name}', '{name} 증가': 'Lisää: {name}' },
}
Object.assign(extendedTranslations.en, dynamicAccessibility.en)
Object.assign(extendedTranslations.ja, dynamicAccessibility.ja)
Object.assign(extendedTranslations.de, dynamicAccessibility.de)
Object.assign(extendedTranslations.da, dynamicAccessibility.da)
Object.assign(extendedTranslations.nb, dynamicAccessibility.nb)
Object.assign(extendedTranslations.fi, dynamicAccessibility.fi)
const hiddenGroupDragTranslations = {
  en: { '이 그룹에 페이지를 추가하려면 여기로 드래그하세요.': 'Drag here to add a page to this group.', '그룹에서 페이지를 꺼내려면 바깥 썸네일이나 빈 곳으로 드래그하세요.': 'Drag this page to an outside thumbnail or empty space to remove it from the group.' },
  ja: { '이 그룹에 페이지를 추가하려면 여기로 드래그하세요.': 'このグループにページを追加するには、ここにドラッグしてください。', '그룹에서 페이지를 꺼내려면 바깥 썸네일이나 빈 곳으로 드래그하세요.': 'グループからページを外すには、外側のサムネイルか空きスペースへドラッグしてください。' },
  de: { '이 그룹에 페이지를 추가하려면 여기로 드래그하세요.': 'Zum Hinzufügen einer Seite hierher ziehen.', '그룹에서 페이지를 꺼내려면 바깥 썸네일이나 빈 곳으로 드래그하세요.': 'Zum Entfernen aus der Gruppe auf eine externe Miniaturansicht oder freie Fläche ziehen.' },
  da: { '이 그룹에 페이지를 추가하려면 여기로 드래그하세요.': 'Træk hertil for at føje en side til gruppen.', '그룹에서 페이지를 꺼내려면 바깥 썸네일이나 빈 곳으로 드래그하세요.': 'Træk siden til en miniature uden for gruppen eller et tomt område for at fjerne den.' },
  nb: { '이 그룹에 페이지를 추가하려면 여기로 드래그하세요.': 'Dra hit for å legge til en side i gruppen.', '그룹에서 페이지를 꺼내려면 바깥 썸네일이나 빈 곳으로 드래그하세요.': 'Dra siden til en miniatyr utenfor gruppen eller et tomt område for å fjerne den.' },
  fi: { '이 그룹에 페이지를 추가하려면 여기로 드래그하세요.': 'Lisää sivu tähän ryhmään vetämällä se tähän.', '그룹에서 페이지를 꺼내려면 바깥 썸네일이나 빈 곳으로 드래그하세요.': 'Poista sivu ryhmästä vetämällä se ulkopuoliseen pikkukuvaan tai tyhjään tilaan.' },
}
Object.assign(extendedTranslations.en, hiddenGroupDragTranslations.en)
Object.assign(extendedTranslations.ja, hiddenGroupDragTranslations.ja)
Object.assign(extendedTranslations.de, hiddenGroupDragTranslations.de)
Object.assign(extendedTranslations.da, hiddenGroupDragTranslations.da)
Object.assign(extendedTranslations.nb, hiddenGroupDragTranslations.nb)
Object.assign(extendedTranslations.fi, hiddenGroupDragTranslations.fi)
const regionHighlightTranslations = {
  en: { '구간 강조': 'Area highlight', '구간 강조 설정': 'Area highlight settings', '구간 강조 색상': 'Highlight color', '구간 강조 투명도': 'Highlight opacity', '구간 강조 영역': 'Highlighted area' },
  ja: { '구간 강조': '範囲ハイライト', '구간 강조 설정': '範囲ハイライト設定', '구간 강조 색상': 'ハイライトの色', '구간 강조 투명도': 'ハイライトの不透明度', '구간 강조 영역': 'ハイライト範囲' },
  de: { '구간 강조': 'Bereich markieren', '구간 강조 설정': 'Einstellungen für Bereichsmarkierung', '구간 강조 색상': 'Markierungsfarbe', '구간 강조 투명도': 'Deckkraft der Markierung', '구간 강조 영역': 'Markierter Bereich' },
  da: { '구간 강조': 'Områdehighlight', '구간 강조 설정': 'Indstillinger for områdehighlight', '구간 강조 색상': 'Highlightfarve', '구간 강조 투명도': 'Highlightgennemsigtighed', '구간 강조 영역': 'Markeret område' },
  nb: { '구간 강조': 'Områdeutheving', '구간 강조 설정': 'Innstillinger for områdeutheving', '구간 강조 색상': 'Uthevingsfarge', '구간 강조 투명도': 'Gjennomsiktighet for utheving', '구간 강조 영역': 'Uthevet område' },
  fi: { '구간 강조': 'Aluekorostus', '구간 강조 설정': 'Aluekorostuksen asetukset', '구간 강조 색상': 'Korostusväri', '구간 강조 투명도': 'Korostuksen peittävyys', '구간 강조 영역': 'Korostettu alue' },
}
Object.assign(extendedTranslations.en, regionHighlightTranslations.en)
Object.assign(extendedTranslations.ja, regionHighlightTranslations.ja)
Object.assign(extendedTranslations.de, regionHighlightTranslations.de)
Object.assign(extendedTranslations.da, regionHighlightTranslations.da)
Object.assign(extendedTranslations.nb, regionHighlightTranslations.nb)
Object.assign(extendedTranslations.fi, regionHighlightTranslations.fi)

const thumbnailGroupTranslations: Record<string, Record<string, string>> = {
  en: {
    '그룹 추가': 'Add group', '썸네일 그룹': 'Thumbnail groups', '그룹 이름': 'Group name', '그룹 이름 입력': 'Enter a group name',
    '그룹 이름은 비워 둘 수 없습니다.': 'Group name cannot be empty.', '그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Could not save the group. Check available storage.',
    '그룹 설정': 'Group settings', '그룹 설정: {name}': 'Settings for group: {name}', '그룹 설정: {name}, 페이지 {count}개': 'Settings for group: {name}, {count} pages',
    '그룹 {name}, 페이지 {count}개': 'Group {name}, {count} pages', '그룹 {name}의 페이지': 'Pages in {name}', '{count}개 페이지': '{count} pages', '그룹 해제': 'Ungroup',
  },
  ja: {
    '그룹 추가': 'グループを追加', '썸네일 그룹': 'サムネイルグループ', '그룹 이름': 'グループ名', '그룹 이름 입력': 'グループ名を入力',
    '그룹 이름은 비워 둘 수 없습니다.': 'グループ名を入力してください。', '그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'グループを保存できませんでした。空き容量を確認してください。',
    '그룹 설정': 'グループ設定', '그룹 설정: {name}': 'グループ設定: {name}', '그룹 설정: {name}, 페이지 {count}개': 'グループ設定: {name}、{count}ページ',
    '그룹 {name}, 페이지 {count}개': '{name}グループ、{count}ページ', '그룹 {name}의 페이지': '{name}のページ', '{count}개 페이지': '{count}ページ', '그룹 해제': 'グループ解除',
  },
  de: {
    '그룹 추가': 'Gruppe hinzufügen', '썸네일 그룹': 'Thumbnail-Gruppen', '그룹 이름': 'Gruppenname', '그룹 이름 입력': 'Gruppennamen eingeben',
    '그룹 이름은 비워 둘 수 없습니다.': 'Der Gruppenname darf nicht leer sein.', '그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Gruppe konnte nicht gespeichert werden. Speicherplatz prüfen.',
    '그룹 설정': 'Gruppeneinstellungen', '그룹 설정: {name}': 'Einstellungen für {name}', '그룹 설정: {name}, 페이지 {count}개': 'Einstellungen für {name}, {count} Seiten',
    '그룹 {name}, 페이지 {count}개': 'Gruppe {name}, {count} Seiten', '그룹 {name}의 페이지': 'Seiten in {name}', '{count}개 페이지': '{count} Seiten', '그룹 해제': 'Gruppierung aufheben',
  },
  da: {
    '그룹 추가': 'Tilføj gruppe', '썸네일 그룹': 'Miniaturegrupper', '그룹 이름': 'Gruppenavn', '그룹 이름 입력': 'Indtast gruppenavn',
    '그룹 이름은 비워 둘 수 없습니다.': 'Gruppenavnet må ikke være tomt.', '그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Gruppen kunne ikke gemmes. Kontrollér lagerpladsen.',
    '그룹 설정': 'Gruppeindstillinger', '그룹 설정: {name}': 'Indstillinger for {name}', '그룹 설정: {name}, 페이지 {count}개': 'Indstillinger for {name}, {count} sider',
    '그룹 {name}, 페이지 {count}개': 'Gruppen {name}, {count} sider', '그룹 {name}의 페이지': 'Sider i {name}', '{count}개 페이지': '{count} sider', '그룹 해제': 'Ophæv gruppering',
  },
  nb: {
    '그룹 추가': 'Legg til gruppe', '썸네일 그룹': 'Miniatyrgrupper', '그룹 이름': 'Gruppenavn', '그룹 이름 입력': 'Skriv inn gruppenavn',
    '그룹 이름은 비워 둘 수 없습니다.': 'Gruppenavnet kan ikke være tomt.', '그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Kunne ikke lagre gruppen. Kontroller lagringsplassen.',
    '그룹 설정': 'Gruppeinnstillinger', '그룹 설정: {name}': 'Innstillinger for {name}', '그룹 설정: {name}, 페이지 {count}개': 'Innstillinger for {name}, {count} sider',
    '그룹 {name}, 페이지 {count}개': 'Gruppen {name}, {count} sider', '그룹 {name}의 페이지': 'Sider i {name}', '{count}개 페이지': '{count} sider', '그룹 해제': 'Opphev gruppering',
  },
  fi: {
    '그룹 추가': 'Lisää ryhmä', '썸네일 그룹': 'Pikkukuvaryhmät', '그룹 이름': 'Ryhmän nimi', '그룹 이름 입력': 'Kirjoita ryhmän nimi',
    '그룹 이름은 비워 둘 수 없습니다.': 'Ryhmän nimi ei voi olla tyhjä.', '그룹을 저장하지 못했습니다. 저장 공간을 확인해 주세요.': 'Ryhmän tallennus epäonnistui. Tarkista tallennustila.',
    '그룹 설정': 'Ryhmän asetukset', '그룹 설정: {name}': 'Ryhmän {name} asetukset', '그룹 설정: {name}, 페이지 {count}개': 'Ryhmän {name} asetukset, {count} sivua',
    '그룹 {name}, 페이지 {count}개': 'Ryhmä {name}, {count} sivua', '그룹 {name}의 페이지': 'Ryhmän {name} sivut', '{count}개 페이지': '{count} sivua', '그룹 해제': 'Poista ryhmittely',
  },
}
Object.assign(extendedTranslations.en, thumbnailGroupTranslations.en)
Object.assign(extendedTranslations.ja, thumbnailGroupTranslations.ja)
Object.assign(extendedTranslations.de, thumbnailGroupTranslations.de)
Object.assign(extendedTranslations.da, thumbnailGroupTranslations.da)
Object.assign(extendedTranslations.nb, thumbnailGroupTranslations.nb)
Object.assign(extendedTranslations.fi, thumbnailGroupTranslations.fi)

Object.assign(extendedTranslations.en, {
  '타임랩': 'Lap times', '타임랩 및 카운터': 'Counter and lap times', '타임랩 기록이 없습니다.': 'No lap records yet.', '더 보기': 'Show more',
  '현재 단 입력': 'Edit current row', '단 번호 입력': 'Row number', '1에서 9999 사이의 정수를 입력하세요.': 'Enter a whole number from 1 to 9999.',
  '+1단': '+1 row', '−1단': '−1 row', '일시정지를 누르지 않아 마지막 저장 이후 측정한 시간은 누적 작업시간에 저장되지 않습니다.': 'Time measured since the last save will not be added to total work time because the timer was not paused.',
})
Object.assign(extendedTranslations.ja, {
  '타임랩': 'ラップタイム', '타임랩 및 카운터': 'カウンターとラップタイム', '타임랩 기록이 없습니다.': 'ラップ記録はありません。', '더 보기': 'さらに表示',
  '현재 단 입력': '現在の段を編集', '단 번호 입력': '段番号', '1에서 9999 사이의 정수를 입력하세요.': '1〜9999の整数を入力してください。',
  '+1단': '+1段', '−1단': '−1段', '일시정지를 누르지 않아 마지막 저장 이후 측정한 시간은 누적 작업시간에 저장되지 않습니다.': '一時停止していないため、前回保存後に計測した時間は累計作業時間に加算されません。',
})
Object.assign(extendedTranslations.de, {
  '타임랩': 'Rundenzeiten', '타임랩 및 카운터': 'Reihenzähler und Rundenzeiten', '타임랩 기록이 없습니다.': 'Noch keine Rundenzeiten.', '더 보기': 'Mehr anzeigen',
  '현재 단 입력': 'Aktuelle Reihe bearbeiten', '단 번호 입력': 'Reihennummer', '1에서 9999 사이의 정수를 입력하세요.': 'Geben Sie eine ganze Zahl von 1 bis 9999 ein.',
  '+1단': '+1 Reihe', '−1단': '−1 Reihe', '일시정지를 누르지 않아 마지막 저장 이후 측정한 시간은 누적 작업시간에 저장되지 않습니다.': 'Die seit dem letzten Speichern gemessene Zeit wird nicht zur Gesamtarbeitszeit addiert, weil der Timer nicht pausiert wurde.',
})
Object.assign(extendedTranslations.da, {
  '타임랩': 'Rundetider', '타임랩 및 카운터': 'Rundetæller og rundetider', '타임랩 기록이 없습니다.': 'Ingen rundetider endnu.', '더 보기': 'Vis flere',
  '현재 단 입력': 'Rediger aktuel omgang', '단 번호 입력': 'Omgangsnummer', '1에서 9999 사이의 정수를 입력하세요.': 'Indtast et helt tal fra 1 til 9999.',
  '+1단': '+1 omgang', '−1단': '−1 omgang', '일시정지를 누르지 않아 마지막 저장 이후 측정한 시간은 누적 작업시간에 저장되지 않습니다.': 'Tiden siden sidste lagring lægges ikke til den samlede arbejdstid, fordi timeren ikke blev sat på pause.',
})
Object.assign(extendedTranslations.nb, {
  '타임랩': 'Rundetider', '타임랩 및 카운터': 'Radeteller og rundetider', '타임랩 기록이 없습니다.': 'Ingen rundetider ennå.', '더 보기': 'Vis flere',
  '현재 단 입력': 'Rediger gjeldende omgang', '단 번호 입력': 'Omgangsnummer', '1에서 9999 사이의 정수를 입력하세요.': 'Skriv inn et heltall fra 1 til 9999.',
  '+1단': '+1 omgang', '−1단': '−1 omgang', '일시정지를 누르지 않아 마지막 저장 이후 측정한 시간은 누적 작업시간에 저장되지 않습니다.': 'Tiden siden siste lagring legges ikke til samlet arbeidstid fordi tidtakeren ikke ble satt på pause.',
})
Object.assign(extendedTranslations.fi, {
  '타임랩': 'Kierrosajat', '타임랩 및 카운터': 'Kerroslaskuri ja kierrosajat', '타임랩 기록이 없습니다.': 'Ei vielä kierrosaikoja.', '더 보기': 'Näytä lisää',
  '현재 단 입력': 'Muokkaa nykyistä kerrosta', '단 번호 입력': 'Kerrosnumero', '1에서 9999 사이의 정수를 입력하세요.': 'Anna kokonaisluku väliltä 1–9999.',
  '+1단': '+1 kerros', '−1단': '−1 kerros', '일시정지를 누르지 않아 마지막 저장 이후 측정한 시간은 누적 작업시간에 저장되지 않습니다.': 'Edellisen tallennuksen jälkeen mitattua aikaa ei lisätä kokonaistyöaikaan, koska ajastinta ei keskeytetty.',
})
